.\" @(#)ellipse.1 - 1.1
.nr LL 5.5i
.ad b
.hy 1
.TH ELLIPSE 1 2/20/89 "USGS/OEMG Systems"
.SH NAME
ellipse - generate ellipsoid constants
.SH SYNOPSIS
.B ellipse
[
.I name
]
.SH DESCRIPTION
.P
.B Ellipse
provides a convenient and more accurate
method to select standard ellipsoidal
parameters with acronymic name rather than having to lookup and
enter the actual numeric values.
The output to standard output of the constant values
is in the form
.RS 8
 
 +a=major +es=eccent,
 
.RE
where
.I major
is the ellipsoid major axis in
meters and
.I eccent
is the squared ellipsoid eccentricity.
.P
If the name is omitted from the execution line
a list will be made of available
.B names
and identification of the ellipsoids to standard output.
.SH EXAMPLE
The following ussage of
.B ellipse
.RS 5
 
 \f(CWproj +proj=poly +lon_0=135e `ellipse aust_ntl` data\fR
 
.RE
will place the Australian National ellipsoid
constants into the argument list of program
.B proj.
.SH SEE ALSO
Program
.B proj(1).
.SH DIAGNOSTICS
An invalid name will cause a message to standard error and constant
output will be suppressed.
.SH AUTHOR/MAINTENANCE
Gerald I. Evenden, USGS, Woods Hole, MA.
