.\" @(#)proj.1 - 3.5
.nr LL 5.5i
.ad b
.hy 1
.TH PROJ 1 "90/05/08 Rel. 3, Ver. 1" "USGS"
.SH NAME
proj \- forward cartographic projection filter
.br
invproj \- inverse cartographic projection filter
.SH SYNOPSIS
.B proj
[
.B \-bcefimorstTwW
[
.I args
] ] [
.B +args
]
file[s]
.br
.B invproj
[
.B \-bcefimorstTwW
[
.I args
] ] [
.B +args
]
file[s]
.SH DESCRIPTION
.I Proj
and
.I invproj
perform respective forward and inverse transformation of cartographic data
to or from cartesian data with a wide range of selectable projection functions.
.PP
The following control parameters can appear in any order:
.TP
.BI \-b
Special option for binary coordinate data input and output
through standard input and standard output.
Data is assumed to be in system type
.I double
floating point words.
This option is to be used when
.B proj
is a
.I son
process and allows bypassing formatting operations.
.TP
.BI \-i
Selects binary input only (see
.B \-b option).
.TP
.BI \-o
Selects binary output only (see
.B \-b option).
.TP
.BI \-t "a"
.I A
specifies a character employed as the first character to denote
a control line to be passed through without processing.
This option applicable to ascii input only.
(# is the default value).
.TP
.BI \-e " string"
.I String
is an arbitrary string to be output if an error is detected during
data transformations.
The default value is: *\et*.
Note that if the
.B \-b,
.B \-i
or
.B \-o
options are employed, an error is returned as
.I HUGE
value for both return values.
.TP
.BI \-c " file"
.I File
is the source file name of additional + option control data for the projection
procedures.
.TP
.BI \-r
This options reverses the order of the
expected input from longitude-latitude or x-y to latitude-longitude or y-x.
.TP
.BI \-s
This options reverses the order of the
output from x-y or longitude-latitude to y-x or latitude-longitude.
.TP
.BI \-m " mult"
The cartesian data may be scaled by the
.I mult
parameter.
When processing data in a forward projection mode the
cartesian output values are multiplied by
.I mult
otherwise the input cartesian values are divided by
.I mult
before inverse projection.
If the first two characters of
.I mult
are 1/ or 1: then the reciprocal value of
.I mult
is employed.
.TP
.BI \-f " format"
.I Format
is a
.I printf
format string to control the form of the output values.
For inverse projections, the output will be in degrees when this option
is employed.
If a format is specified for inverse projection the
output data will be in decimal degrees.
The default format is \(``%.2f\('' for forward projection and DMS
for inverse.
.TP
.BI \-[w|W] n
.I N
is the number of significant fractional digits to employ for
seconds output (when the option is not specified,
.B \-w3
is assumed).
When
.B \-W
is employed the fields will be constant width with leading zeroes.
.TP
.BI \-T " ulow,uhi,vlow,vhi,res[,umax,vmax]"
This option creates a set of bivariate Chebyshev polynomial
coefficients that approximate the selected cartographic projection on
.I stdout.
The values
.I low
and
.I hi
denote the range of the input where the
.I u
or
.I v
prefixes apply to respective longitude-x or latitude-y
depending upon whether a forward or inverse projection is selected.
.I Res
is an integer number specifying the power of 10 precision of the
approximation.
For example, a
.I res
of -3 specifies an approximation accuracy better than .001.
.I Umax,
and
.I vmax
specify maximum degree of the polynomials (default: 15).
See also:
.B fproj(1).
.PP
The
.B +args
run-line arguments are associated with cartographic parameters
and usage varies with projection and for a complete description see
.I "Cartographic Projection Procedures for the UNIX Environment\(emA User's Manual" )
They may be either entered on the run line where they must be preceeded
by the + symbol or specified in the file reference by the
.B \-c
option where the + prefix is optional.
The options are processed in left to right order
from the run line followed by processing the entries in the
.B\-c
file.
Reentry of an option is ignored with the first occurance assumed to
be the desired value.
.PP
One or more
.I files
(processed in left to right order)
specify the source of data to be transformed.
A \- will specify the location of processing standard input.
If no files are specified, the input is assumed to be from
.I stdin.
For ASCII input data the two data values must be in the
first two white space separated fields and
when both input and output are ASCII all trailing portions
of the input line are appended to the output line.
.PP
Input geographic data
(longitude and latitude) must be in DMS format and input
cartesian data must be in units consistent with the ellipsoid
major axis or sphere radius units.
Output geographic coordinates will be in DMS
(if the
.B \-w
switch is not employed) and precise to 0.001"
with trailing, zero-valued minute-second fields deleted.
.SH EXAMPLE
The following script
.RS 5
 \f(CWproj +proj=utm +lon_0=112w -r <<EOF
 45d15'33.1"	111.5W
 45d15.551666667N	-111d30
 +45.25919444444	111d30'000w
 EOF\fR
.RE
will perform UTM forward projection with a standard UTM
central meridian nearest longitude 112\(deW.
The geographic values of this example are equivalent and meant
as examples of various forms of DMS input.
The x\-y output data will appear as three lines of:
.RS 5
 \f(CW460769.27	5011648.45
.RE
.SH SEE ALSO
.I "Cartographic Projection Procedures for the UNIX Environment\(emA User's Manual,"
(Evenden, 1990, Open-file report 90\-xxx).
.br
.I "Map Projections Used by the U. S. Geological Survey"
(Snyder, 1984,
USGS Bulletin 1532).
.br
.I "Map Projections\(emA Working Manual"
(Synder, 1988, USGS Prof. Paper 1395).
.br
.I "An Album of Map Projections"
(Snyder & Voxland, 1989, USGS Prof. Paper 1453).
