.nr LL 5.5i
.ad b
.hy 1
.TH NAD27 1 "90/05/08 Rel. 3, Ver. 0" "USGS"
.SH NAME
nad27, for27, inv27 \- NAD27 State Plane Coordinate Systems
.br
nad83, for83, inv83 \- NAD83 State Plane Coordinate Systems
.SH SYNOPSIS
.B nad27
|
.B nad83
[
.I state
]
.br
.BI "for27 | for83" " state_zone"
[
.B \-M
] [
.BI proj "\(emparameters"
] [
.I file
\&... ]
.br
.BI "inv27 | inv83" " state_zone"
[
.B \-M
] [
.BI proj "\(emparameters"
] [
.I file
\&... ]
.SH DESCRIPTION
.B For27,
.B inv27,
.B for83,
and
.B inv83
provide a convenient method for specifications of respective
forward and inverse projection of geographic and State Plane
Coordinates for both North American Datums 27 and 83.
The parameter
.I state_zone
refers to one of the State zone numbers established by the
National Geodetic Survey.
Execution of
.B nad27
or
.B nad83
will produce a complete annotated listing of State zone numbers.
Execution with a state as an argument will limit the list
to zones in that state.
.P
The parameter
.B \-M
allows the specification of
.I meters
as the unit of the cartesian system.
Otherwise the U.S. Surveyor's foot is used
(exact relation of 39.37 inches equals 1 m).
Other control parameters for program
.B proj
may follow including input file names.
.SH CAVEATS
Although some checking of the information contained in
this procedure has been made, the user is cautioned to perform
his own tests against conversions authorized as accurate by
appropriate State or local authorities.
Any discrepencies should be reported to the author.
.SH ACKNOWLEDGEMENTS
The tables were compiled from information distributed
as part of
.SM "GCTP II"
.SM ( NOAA ", 1987)."
.SH FILES
/usr/local/lib/state27
.br
/usr/local/lib/state83
.SH SEE ALSO
Cartographic Projection Procedures for the UNIX Environment\(emA
User's Manual (G.I. Evenden, 1990, admin. rpt.).
.br
proj(1)
.SH AUTHOR/MAINTENANCE
Gerald I. Evenden, USGS, Woods Hole, MA
