
MODULE_TOPDIR = ../..

#the order is relevant
SUBDIRS = \
	dbmi_base \
	dbmi_client \
	stubs \
	dbmi_driver \
	sqlp

include $(MODULE_TOPDIR)/include/Make/Dir.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: subdirs

clean: cleansubdirs

#doxygen:
DOXNAME=dbmi
