#!/bin/sh
# config.sh
# This file was produced by running the XGRASS config script.
# DO NOT EDIT THIS FILE...or else
eunicefix=':'
spitshell='cat'
xgrassinc=''
localbin='/GRASS.bin/4.1/mips/bin'
mansrc='/GRASS.bin/4.1/mips/man'
manext='n'
ldflags='-O -Olimit 2000 -Wf,-XNd8400,-XNp12000 -systype bsd43 '
extraldflags=''
mipsos='bsd'
xincs=' -I/usr/RISCwindows4.0/include -I/usr/RISCwindows4.0/include/X11'
xlibdir=''
xtlibdir=''
xmlibdir='-L/usr/RISCwindows4.0/lib'
cflags='-O -Olimit 2000 -Wf,-XNd8400,-XNp12000 -signed -systype bsd43 -DMips -DBSD -DBSD43 '
cc='cc'
rm='rm -f'
printcommand='lpr %s'
CONFIG=true
