#!/bin/sh
# config.sh
# This file was produced by running the XGRASS config script.
# DO NOT EDIT THIS FILE...or else
eunicefix=':'
spitshell='cat'
xgrassinc=''
localbin='/usr/local/bin'
mansrc='/usr/man/mann'
manext='n'
ldflags='-O '
extraldflags=''
mipsos=''
xincs=' -I/usr/local/include'
xlibdir='-L/usr/X11/lib'
xtlibdir='-L/usr/X11/lib'
xmlibdir='-L/usr/local/lib'
cflags='-O -DBSD '
cc='gcc'
rm='rm -f'
printcommand='cat %s | /bin/lp'
CONFIG=true
