.TH XGEN 1X "11 JULY 1991" "X Version 11"
.SH NAME
xgen - an application generator program
.SH SYNOPSIS
.B "xgen"
[-v] [-c] [-p] [-n] [-help] [-patch] [-version]
[-I\fIdir\fP] [-D\fIname\fP] [-D\fIname=def\fP]
[-display \fIdisplay\fP] [-geometry \fIgeometry\fP] \fIscriptname\fP
.SH DESCRIPTION
.PP
.I Xgen
is a graphical user interface (GUI) generator program that was designed 
to be used for the rapid generation of interfaces (using the OSF/Motif 
widget set) to existing shell level programs. 
A simple, hierarchically-oriented language (see  \fIXgen: an application 
interface generator program\fP included in the \fIxgen\fP distribution) 
allows an interface programmer to define a GUI which 
is used to 1) collect information from the user and 2) execute shell level 
commands based on this information.
.SH OPTIONS
.PP
.TP 8
.B "-v"
put 
.I xgen 
into verbose mode. This causes the display of non-fatal
warnings. Many times 
.I xgen 
developers will echo information to the controlling tty and thus
don't want warning beyond the users control to appear.
.PP
.TP 8
.B "-c"
display control box. The control box is a mechanism for manipulating
the interface during script development. It provides a quit mechanism
and limited job control on background processes started with the 
.B runforeground 
command (see  \fIXgen: an application
interface generator program\fP included in the \fIxgen\fP distribution).
.PP
.TP 8
.B "-p"
This argument allows you to parse the \fIxgen\fP script without
operating the resulting interface (useful during script development).
.PP
.TP 8
.B "-n"
Xgen scripts are passed through the C preprocessor. This argument means do 
not pass thru C preprocessor; see \fIcpp(1)\fP
for details on the C preprocessor.
.PP
.TP 8
.B "-help"
This message will print a usage message.
.PP
.TP 8
.B "-patch"
This argument allows you to print version (patchlevel) information.
.PP
.TP 8
.B "-version"
This argument does the same thing as \fI-patch\fP.
.PP
.TP 8
.B "-I\fIdir\fP"
This argument allows you to add 
.I dir 
to cpp(1) include file search list; see \fIcpp(1)\fP.
.PP
.TP 8
.B "-D\fIname\fP"
This argument allows you to define 
.i
.I name 
as 1 (true) to the C preprocessor; see \fIcpp(1)\fP.
.PP
.TP 8
.B "-D\fIname=def\fP"
This argument allows you to define 
.I name 
as 
.I def 
to the C preprocessor; see \fIcpp(1)\fP.
.PP
.TP 8
.B "-display \fIdisplay\fP"
This argument allows you to specify the server to connect to; see \fIX(1)\fP.
.PP
.TP 8
.B "-geometry \fIgeometry\fP"
This argument allows you to specify the geometry of the control box;
see \fI-c\fP option description.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
To get default host and display number.
.SH SEE ALSO
cpp(1), X(1), \fIXgen: an application interface generator program\fP 
(included in the \fIxgen\fP distribution).
.SH AUTHOR
Kurt Buehler, U.S. Army CERL
