
MODULE_TOPDIR = ../..

LIB_NAME = $(RASTER_LIBNAME)

LIB_OBJS = \
	Box.o\
	Color.o\
	Clr_table.o\
	Cont_abs.o\
	Cont_rel.o\
	Erase.o\
	Flush.o\
	Font.o\
	Get_ncolors.o \
	Get_t_box.o\
	Get_w_box.o\
	Get_w_line.o\
	Get_w_pnt.o\
	Move_abs.o\
	Move_rel.o\
	Panel.o\
	Plydts_abs.o\
	Plydts_rel.o\
	Plylne_abs.o\
	Plylne_rel.o\
	Polygn_abs.o\
	Polygn_rel.o\
	RGB_color.o\
	RGB_ras.o\
	Raster.o\
	Reset_clr.o\
	Reset_clrs.o\
	Returns.o\
	Set_win.o\
	Text.o\
	Text_rot.o\
	Text_size.o\
	cancel.o\
	io.o\
	item_appnd.o\
	item_del.o\
	item_get.o\
	item_list.o\
	item_set.o\
	lists.o\
	pad_create.o\
	pad_cur.o\
	pad_delete.o\
	pad_invent.o\
	pad_list.o\
	pad_select.o\
	parse_mon.o\
	perror.o \
	update.o

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib

