C$NOFLOATCALLS
      SUBROUTINE BDSET(MIN,MAX,GRID,N,SET)
C 
C     THIS SUBROUTINE IS USED TO TEST IF THE BOUNDS ARE A MULTIPLE OF THE 
C     GRID SIZE.  IF NOT THEN THEY ARE MODIFIED UNTIL BOTH ARE MULTIPLES
C      OF THE GRID SIZE.  IT ALSO SETS A FLAG (SET) TO SAY THTAT THEY 
C     HAVE BEEN BMODIFIED.  THE NUMBER OF GRID POINTS BETWEEN MIN AND 
C     MAX IS ALSO GIVEN IN (N).  WHEN THE BOUNDS ARE CHANED THE MIN GOES
C     SMALLER AND THE MAX BECOMES BIGGER. 
C 
      REAL  MIN,MAX,GRID,TOL
      LOGICAL  SET
      DATA  TOL/0.001/
C 
C     GET THE DIFFERANCE AND SEE IF A MULTIPLE OF GRID
      D=(MAX-MIN)/GRID
      N=D 
      IF (ABS(D-N).LT.TOL)  RETURN
C 
C     NOT A MULTIPLE OF GRID SO MODIFY
C 
      M=INT(MIN/GRID) 
C     MAKE MIN SMALLER IF IT IS NEGATIVE SINCE FUNCTION FIX DOESN'T 
      IF (MIN.LT.0.0)  M=M-1
      MIN=M*GRID
C 
C     TAKE CARE OF MAX      MAKE IT BIGGER IF IT IS POSITIVE
      M= INT(MAX/GRID)
      IF (MAX.GT.0.0)  M=M+1
      MAX=M*GRID
C 
      N=(MAX-MIN)/GRID
C     SET FLAG
      SET=.TRUE.
      RETURN
      END 
