	SUBROUTINE FILEOPEN
	LOGICAL GIS
	COMMON/GRASS/GIS
	COMMON/IO/KARD,KPRINT
	CHARACTER*13 F
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C 6/14/88  following variable being added to put output into
C users home directory -- bnoise being run by grass command
C "grass.bnoise" in .tmp directory under current location
C and mapset.
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
	CHARACTER*100 FILENAME
	WRITE(0,10)
10	FORMAT(/' PRINTED OUTPUT IS TO BE DIRECTED TO:'/
     $	' 1 - SCREEN',/,' 2 - FILE'/)
20	WRITE(0,30)
30	FORMAT(' ENTER CHOICE: ')
	READ(5,*) N
	IF(N.LT.1.OR.N.GT.2) GO TO  20
	IF(N.EQ.1) THEN 
      KPRINT=0
      ELSE
C60	WRITE(0,70)
C70	FORMAT(/' ENTER FILENAME: ')
C	READ(5,80)F
C80	FORMAT(A13)
90	KPRINT=16
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C following code being added to get user's home directory name
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
	OPEN(KPRINT,FILE='OUTFILE',STATUS='OLD')
	READ(KPRINT,11) FILENAME
11      FORMAT(A100)
C	WRITE(0,*) FILENAME
	CLOSE(KPRINT)
C	OPEN(KPRINT,FILE=F,STATUS='NEW')
	OPEN(KPRINT,FILE=FILENAME)
	WRITE(0,12)
12    FORMAT(/' Executing LCDN program ...  ')
	ENDIF
99	OPEN(KARD,FILE='BNOISEIN.DAT')
C
C   the following code is for future implementation of
C   nasaplot routine.
C
C	WRITE(0,11)
C11    FORMAT(' OUTPUT IS FOR:'/
C     $       ' 1 - NASAPLOT',/,' 2 - GIS CELL FILE'/)
C21	WRITE(0,30)
C	READ(5,*) N
C	IF(N.LT.1.OR.N.GT.2) GO TO  21
C	IF(N.EQ.1) THEN 
C      GIS = .FALSE.
C	ELSE       
      GIS = .TRUE.
C	ENDIF
	REWIND(KARD)
       RETURN
	END
