CNOFLOATCALLS
C  	INTERFACE TO SUBROUTINE  TIME (N,STR)
C  	CHARACTER*10 STR  [NEAR,REFERENCE]
C  	INTEGER*2 N[VALUE]
C  	END
	FUNCTION SECOND(Z)
	CHARACTER*1  TI(10)
	CALL TIME(10,TI)
	T=((ICHAR(TI(1))-48)*10+ICHAR(TI(2)))*3600.
	T=T+((ICHAR(TI(4))-48)*10+ICHAR(TI(5)))*60.
	T=T+(ICHAR(TI(7))-48)*10+ICHAR(TI(8))
	SECOND=T
	RETURN
	END
	FUNCTION TIMEDIF(TA,TB)
	TIMEDIF=TA-TB
	IF(TIMEDIF.LT.0.)TIMEDIF=TIMEDIF+86400.
	RETURN
	END
