      SUBROUTINE STOPP
	  LOGICAL GIS
	  COMMON/GRASS/GIS
      COMMON /IO/KARD,KPRINT
      DATA IOUT/55/  
      WRITE(KPRINT,10)
   10 FORMAT(1H1///T15,'.....     STOP     .....')
      WRITE(IOUT,100)
 100  FORMAT(1h ,4HSTOP)
	  IF (GIS) THEN
      WRITE(KPRINT,200)
	  ELSE
	  WRITE(KPRINT,201)
	  ENDIF
  200 FORMAT(////T13,'GNOISE INPUT FILE COMPLETED')
  201 FORMAT(////T13,'NASAPLOT INPUT FILE COMPLETED')
      RETURN
      END
