#!/bin/sh
PATH=/grass.src/4.1/sun4/bin:/grass.src/4.1/sun4/scripts:/grass.src/4.1/sun4/garden/bin:$XGHOME/bin:$PATH
export PATH
GISBASE=/grass.src/4.1/sun4
export GISBASE
if test "$XAPPLRESDIR" = ""; then
XAPPLRESDIR=$GISBASE/etc/app-defaults
export XAPPLRESDIR
fi
XGRASSLIBDIR=$XGHOME/lib
export XGRASSLIBDIR
XGRASSHELPDIR=$XGHOME/lib/help
export XGRASSHELPDIR
exec dbx $GISBASE/bin/xgreclass
