#!/bin/sh

# GRASS 5 binary package installation tool
# platform indendent
# This script is not generated by any other process. Make all changes to this
# file.

# $Id$
# 1999-2000 by Markus Neteler, neteler@geog.uni-hannover.de

######################################################
#setting: where to put the GRASS start script:
BINDIR=/usr/local/bin

#setting: standard path of GRASS installation
DESTDIR=/usr/local/grass-5.0b

# Get the major release number to append to grass command name
#NAME_VER=`cat src/CMD/VERSION | head -1 | sed 's/\..*//'`
# this doesnt work without sources!
NAME_VER=5

######################################################
# check for first parameter:
if [ ! "$1" ]
then	echo "

GRASS GIS $NAME_VER binary package installation tool

Usage:        sh grass5install.sh grass_binpackage.tar.gz [dest_dir]

      with:
        grass_binpackage : name of GRASS $NAME_VER binary package   
        [dest_dir] - optional: FULL path name to the installation directory
                     (default: /usr/local/grass$NAME_VER/)

You may need login as root for installation.
"
	exit
fi

# check for second parameter:
if [ "$2" ]
then
  DESTDIR=$2
fi

# check for correct package name:
if test ! -f $1; then 
   echo "ERROR: Wrong package name $1. File does not exists."
   echo ""
   exit
fi

# check, if package is first parameter and in tar.gz compression:
echo $1 |grep bz2
if [ $? -eq 1 ] ; then
    PACKAGETYPE=`file $1`
    echo $PACKAGETYPE  | grep gzip > /dev/null
    if [ $? -eq 1 ] ; then
       echo "ERROR: You need the GRASS binary package in .tar.gz compression or bz2."
       echo ""
       exit
    else
      UNPACK=gunzip
      # is gunzip there?
      which gunzip |grep -v no
      if [ $? -eq 1 ] ; then
        echo "No gunzip installed. Please get from:"
        echo "   http://www.gnu.org/software/gzip/gzip.html"
        exit
      fi
    fi
else
 UNPACK=bunzip2
 # is bunzip2 there?
 which bunzip2 |grep -v no
 if [ $? -eq 1 ] ; then
   echo "No bunzip2 installed. Please get from:"
   echo "   http://sources.redhat.com/bzip2/index.html"
   exit
 fi
fi

echo "Using $UNPACK decompressor..."

# Start the installation job...
echo "GRASS GIS $NAME_VER binary package installation tool"
echo ""
echo "The package $1 seems to be o.k."
echo " Proceeding..."
echo ""
echo "Checking and creating installation directory..."
echo "Installing to $DESTDIR"

if [ ! -d "$DESTDIR" ] ;
then
        #check if a word "grass" is in string $DESTDIR
        echo $DESTDIR |grep -w "grass"
        if [ $? -eq 1 ] ; then
            echo "WARNING: Your destination path $DESTDIR does not contain the word 'grass'"
            echo "Continue (y/n)?"
            read ans         
            if [ "$ans" = "n" -o "$ans" = "N" ] ; then
             exit
            fi
        fi

        mkdir -p $DESTDIR
        if [ $? -eq 1 ] ; then
          echo "An error occured! Exiting."
          exit
        fi
else
     if [ -d $DESTDIR/bin ] ; then
          echo ""
          echo "ERROR: Old GRASS distribution existing in $DESTDIR!"
          echo "Remove first!"
          exit
     else
          #check if a word "grass" is in string $DESTDIR
          echo $DESTDIR |grep -w "grass"
          if [ $? -eq 1 ] ; then
            echo "WARNING: Your destination path $DESTDIR does not contain the word 'grass'"
            echo "Continue (y/n)?"
            read ans         
            if [ "$ans" = "n" -o "$ans" = "N" ] ; then
             exit
            fi
          fi
     fi        
fi

echo "Installing GRASS binaries into $DESTDIR"
echo ""

echo "Uncompressing the package and extracting to target directory..."
$UNPACK -c $1 |tar -C $DESTDIR -xvf -
if [ $? -eq 1 ] ; then
     echo "An error occured/user break! Exiting."
     exit
fi

##Creating start script
if [ ! -d "$BINDIR" ] ;
then
 BINDIR=/usr/bin
fi
echo "Creating start script: $BINDIR/grass$NAME_VER"
echo ":"                          >$BINDIR/grass$NAME_VER
if [ $? -eq 1 ] ; then
          echo "An error occured! Exiting."
          echo "You must be 'root' to install into $BINDIR"
          exit
fi
echo "GISBASE=$DESTDIR"           >>$BINDIR/grass$NAME_VER
echo "export GISBASE"             >>$BINDIR/grass$NAME_VER
echo "exec \$GISBASE/etc/Init.sh" >>$BINDIR/grass$NAME_VER
chmod ugo+x $BINDIR/grass$NAME_VER


echo "Creating the locks directory for monitors..."
SERVERNAME=`uname -n | sed -e "s/\..*//"`
rm -rf $DESTDIR/locks/*
mkdir $DESTDIR/locks/$SERVERNAME
chmod -R 1777 $DESTDIR/locks


# update paths in etc/monitorcap:
cp $DESTDIR/etc/monitorcap $DESTDIR/etc/monitorcap.orig
NEWPATH=$DESTDIR
sed 's*/usr/local/grass-5.0b*'${NEWPATH}'*g' $DESTDIR/etc/monitorcap.orig > $DESTDIR/etc/monitorcap


echo""
echo "Creating the monitor fifos..."
rm -f $DESTDIR/dev/fifo.*
# create script with paths updated:
sed 's*/usr/local/grass-5.0b*'${NEWPATH}'*g' $DESTDIR/dev/create_fifos.sh > $DESTDIR/dev/create_fifos_new.sh
chmod ugo+x $DESTDIR/dev/create_fifos_new.sh
sh $DESTDIR/dev/create_fifos_new.sh


echo "Installation finished. Start GRASS $NAME_VER with"
echo "    grass$NAME_VER"
echo ""
echo "The graphical user interface can be started within GRASS GIS."
echo ""
echo "Welcome to GRASS GIS. Enjoy this open source GNU GRASS GIS!"
echo ""
