
MODULE_TOPDIR = ..

SUBDIRS = \
	g.access \
	g.ask \
	g.filename \
	g.findfile \
	g.gisenv \
	g.mapset \
	g.mapsets \
	g.parser \
	g.proj \
	g.region \
	g3.region \
	g.setproj \
	g.tempfile \
	g.version \
	manage

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs

clean: cleansubdirs
