
MODULE_TOPDIR = ..

SUBDIRS = \
	g.gisenv \
	g.mapsets \
	g.parser \
	g.region \
	g.setproj \
	g.tempfile \
	g.version \
	manage

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs

clean: cleansubdirs

