MODULE_TOPDIR = ../..

PGM = g.setproj
EXTRA_CFLAGS = $(GDALCFLAGS)

LIBES     = $(GPROJLIB) $(GISLIB)
DEPENDENCIES= $(GISDEP) $(GPROJDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: inter
