.TH i.out.erdas
.SH NAME
\fIi.out.erdas\fR \-Creates ERDAS files from raster files.
.br
.I "(GRASS Raster Program)"
.SH SYNOPSIS
\fBi.out.erdas\fR
.br
\fBi.out.erdas help\fR
.br
\fBi.out.erdas\fR [\fB\-lbs\fR] \fBinput=\fIname[,name,...]\fR \fBouput=\fIname

.SH DESCRIPTION
This program creates ERDAS files from raster files.  It
creates one band for each raster file, up to the signed 16-bit
limit at 32767.
.br
Only ERDAS version 7.4 files can be created in 8-bit or 16-bit formats. Either byte
order is acceptable to the original format spec,
so byte swapping can be necessary on any platform.
.br

.SH "COMMAND LINE OPTIONS"
.LP
Flags:
  -l   List the ERDAS header only
  -b   Output 16-bit image (default 8)
  -s   Force byte swapping

Parameters:
  input   Input raster layers.
  ouput   Erdas output file name
.SH "SEE ALSO"
r.support, i.group i.in.erdas

.SH NOTES
This whole program is new and under-tested. Use with some caution,
if only to make sure that software will read these files.
.br

.SH AUTHOR
Angus Carr.