N=tbl -TX man.version $wd\/man.header $? | nroff | col -b > $@
all: list
cat2/Dtext: man2/Dtext ;  $N
cat2/Dstop.mon: man2/Dstop.mon ;  $N
cat2/Dwhich.mon: man2/Dwhich.mon ;  $N
cat2/Dtitle: man2/Dtitle ;  $N
cat2/Dvect: man2/Dvect ;  $N
cat2/Gmapcalc: man2/Gmapcalc ;  $N
cat2/Dwhere: man2/Dwhere ;  $N
cat2/Dwhich: man2/Dwhich ;  $N
cat2/Dselect.mon: man2/Dselect.mon ;  $N
cat2/Gask: man2/Gask ;  $N
cat2/Mwindow.ll: man2/Mwindow.ll ;  $N
cat2/Gcopy: man2/Gcopy ;  $N
cat2/Ggrow: man2/Ggrow ;  $N
cat2/Ginfer: man2/Ginfer ;  $N
cat2/Glist: man2/Glist ;  $N
cat2/Dwhat: man2/Dwhat ;  $N
cat2/Greclass: man2/Greclass ;  $N
cat2/Gremove: man2/Gremove ;  $N
cat2/Grename: man2/Grename ;  $N
cat2/Gstats: man2/Gstats ;  $N
cat2/Gwindow: man2/Gwindow ;  $N
cat2/Pmap: man2/Pmap ;  $N
cat2/Gmfilter: man2/Gmfilter ;  $N
cat2/DINTRO: man2/DINTRO ;  $N
cat2/Mrot90: man2/Mrot90 ;  $N
cat2/Mimport.ll: man2/Mimport.ll ;  $N
cat2/Mdem.examine: man2/Mdem.examine ;  $N
cat2/Gmapsets: man2/Gmapsets ;  $N
cat2/Pscreen: man2/Pscreen ;  $N
cat2/Gcost: man2/Gcost ;  $N
cat2/Dclear.screen: man2/Dclear.screen ;  $N
cat2/Gdrain: man2/Gdrain ;  $N
cat2/Gpat.place: man2/Gpat.place ;  $N
cat2/D3d: man2/D3d ;  $N
cat2/Glos: man2/Glos ;  $N
cat2/Gdescribe: man2/Gdescribe ;  $N
cat2/Gcell.colors: man2/Gcell.colors ;  $N
cat2/Gclump: man2/Gclump ;  $N
cat2/Grandom: man2/Grandom ;  $N
cat2/Gdistance: man2/Gdistance ;  $N
cat2/Pselect: man2/Pselect ;  $N
cat2/Mdted.examine: man2/Mdted.examine ;  $N
cat2/Mdted.extract: man2/Mdted.extract ;  $N
cat2/Mdem.extract: man2/Mdem.extract ;  $N
cat2/Gslope.aspect: man2/Gslope.aspect ;  $N
cat2/Gfindfile: man2/Gfindfile ;  $N
cat2/Gdumpcell: man2/Gdumpcell ;  $N
cat2/Gresample: man2/Gresample ;  $N
cat2/Mll2gc: man2/Mll2gc ;  $N
cat2/D3d.view: man2/D3d.view ;  $N
cat2/Grescale: man2/Grescale ;  $N
cat2/Dslide.show: man2/Dslide.show ;  $N
cat2/Dwhat.once: man2/Dwhat.once ;  $N
cat2/Dlabel: man2/Dlabel ;  $N
cat2/Gweight: man2/Gweight ;  $N
cat2/Dshow.fonts: man2/Dshow.fonts ;  $N
cat2/Mgc2ll: man2/Mgc2ll ;  $N
cat2/Mdshift: man2/Mdshift ;  $N
cat2/Mimportcell: man2/Mimportcell ;  $N
cat2/Gsites: man2/Gsites ;  $N
cat2/Dfont: man2/Dfont ;  $N
cat2/Doverlay: man2/Doverlay ;  $N
cat2/Greport: man2/Greport ;  $N
cat2/Dmenu: man2/Dmenu ;  $N
cat2/Dcolortable: man2/Dcolortable ;  $N
cat2/Dmeasure: man2/Dmeasure ;  $N
cat2/Glayer.info: man2/Glayer.info ;  $N
cat2/Dvect.dlg: man2/Dvect.dlg ;  $N
cat2/Gcross: man2/Gcross ;  $N
cat2/Vpatch: man2/Vpatch ;  $N
cat2/Gpoly: man2/Gpoly ;  $N
cat2/V.mkquads: man2/V.mkquads ;  $N
cat2/V.mkgrid: man2/V.mkgrid ;  $N
cat2/Dsplit: man2/Dsplit ;  $N
cat2/Vexport.dlg: man2/Vexport.dlg ;  $N
cat2/Gwhat: man2/Gwhat ;  $N
cat2/Gfilename: man2/Gfilename ;  $N
cat2/Vprune: man2/Vprune ;  $N
cat2/Vmake.sites: man2/Vmake.sites ;  $N
cat2/Gcats: man2/Gcats ;  $N
cat2/Gaverage: man2/Gaverage ;  $N
cat2/Gcovar: man2/Gcovar ;  $N
cat2/Gcorr: man2/Gcorr ;  $N
cat2/Gpoints.surf: man2/Gpoints.surf ;  $N
cat2/Gsurface: man2/Gsurface ;  $N
cat3/monitorcap: man3/monitorcap ;  $N
cat3/paint: man3/paint ;  $N
cat3/imagery: man3/imagery ;  $N
cat3/sites.format: man3/sites.format ;  $N
cat3/sites.S: man3/sites.S ;  $N
cat3/sites.report: man3/sites.report ;  $N
cat3/sites.occur: man3/sites.occur ;  $N
list:  cat2/Dtext cat2/Dstop.mon cat2/Dwhich.mon cat2/Dtitle cat2/Dvect cat2/Gmapcalc cat2/Dwhere cat2/Dwhich cat2/Dselect.mon cat2/Gask cat2/Mwindow.ll cat2/Gcopy cat2/Ggrow cat2/Ginfer cat2/Glist cat2/Dwhat cat2/Greclass cat2/Gremove cat2/Grename cat2/Gstats cat2/Gwindow cat2/Pmap cat2/Gmfilter cat2/DINTRO cat2/Mrot90 cat2/Mimport.ll cat2/Mdem.examine cat2/Gmapsets cat2/Pscreen cat2/Gcost cat2/Dclear.screen cat2/Gdrain cat2/Gpat.place cat2/D3d cat2/Glos cat2/Gdescribe cat2/Gcell.colors cat2/Gclump cat2/Grandom cat2/Gdistance cat2/Pselect cat2/Mdted.examine cat2/Mdted.extract cat2/Mdem.extract cat2/Gslope.aspect cat2/Gfindfile cat2/Gdumpcell cat2/Gresample cat2/Mll2gc cat2/D3d.view cat2/Grescale cat2/Dslide.show cat2/Dwhat.once cat2/Dlabel cat2/Gweight cat2/Dshow.fonts cat2/Mgc2ll cat2/Mdshift cat2/Mimportcell cat2/Gsites cat2/Dfont cat2/Doverlay cat2/Greport cat2/Dmenu cat2/Dcolortable cat2/Dmeasure cat2/Glayer.info cat2/Dvect.dlg cat2/Gcross cat2/Vpatch cat2/Gpoly cat2/V.mkquads cat2/V.mkgrid cat2/Dsplit cat2/Vexport.dlg cat2/Gwhat cat2/Gfilename cat2/Vprune cat2/Vmake.sites cat2/Gcats cat2/Gaverage cat2/Gcovar cat2/Gcorr cat2/Gpoints.surf cat2/Gsurface cat3/monitorcap cat3/paint cat3/imagery cat3/sites.format cat3/sites.S cat3/sites.report cat3/sites.occur
