
MODULE_TOPDIR = ../..

PGM = v.in.sites

LIBES = $(VECTLIB) $(DBMILIB) $(GISLIB) $(VASKLIB) $(DATETIMELIB)
DEPENDENCIES= $(VECTDEP) $(GISDEP) $(DBMIDEP) $(VASKLIB) $(DATETIMELIB)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
