int translate_quad ();
int interp_call ();
int INPUT ();
int secpar_loop ();
int OUTGR ();
int min1 ();
int max1 ();
double amax1 ();
double amin1 ();
double crst ();
int crstg ();
int COGRR1 ();
int POINT ();
int LINEQS ();
void lntab();
void s_table();
void spline();
