
MODULE_TOPDIR = ../..

PGM = g.mapsets
LIBES     = $(GISLIB) $(VASKLIB)

INTER_OBJS = \
	main_inter.o\
	dsply_path.o\
	dsply_maps.o\
	get_maps.o\
	get_path.o\
	set_path.o\
	scan_int.o

CMD_OBJS = \
	main_cmd.o \
	dsply_path.o \
	dsply_maps.o \
	get_maps.o

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




