/* draw_grid.c */
__inline__ int __stat(__const char *, struct stat *);
__inline__ int stat(__const char *, struct stat *);
__inline__ int __lstat(__const char *, struct stat *);
__inline__ int lstat(__const char *, struct stat *);
__inline__ int __fstat(int, struct stat *);
__inline__ int fstat(int, struct stat *);
__inline__ int __mknod(__const char *, __mode_t, __dev_t);
__inline__ int mknod(__const char *, __mode_t, __dev_t);
int draw_grid(void);
/* edit.c */
__inline__ int __stat(__const char *, struct stat *);
__inline__ int stat(__const char *, struct stat *);
__inline__ int __lstat(__const char *, struct stat *);
__inline__ int lstat(__const char *, struct stat *);
__inline__ int __fstat(int, struct stat *);
__inline__ int fstat(int, struct stat *);
__inline__ int __mknod(__const char *, __mode_t, __dev_t);
__inline__ int mknod(__const char *, __mode_t, __dev_t);
int edit(void);
int edit_mouse_info(void);
int edit_mouse_info2(DCELL, DCELL);
int use_mouse(void);
/* main.c */
__inline__ int __stat(__const char *, struct stat *);
__inline__ int stat(__const char *, struct stat *);
__inline__ int __lstat(__const char *, struct stat *);
__inline__ int lstat(__const char *, struct stat *);
__inline__ int __fstat(int, struct stat *);
__inline__ int fstat(int, struct stat *);
__inline__ int __mknod(__const char *, __mode_t, __dev_t);
__inline__ int mknod(__const char *, __mode_t, __dev_t);
int main(int, char **);
int do_edit(int, int, double);
int error(int, char [128]);
int ext(void);
/* menu.c */
__inline__ int __stat(__const char *, struct stat *);
__inline__ int stat(__const char *, struct stat *);
__inline__ int __lstat(__const char *, struct stat *);
__inline__ int lstat(__const char *, struct stat *);
__inline__ int __fstat(int, struct stat *);
__inline__ int fstat(int, struct stat *);
__inline__ int __mknod(__const char *, __mode_t, __dev_t);
__inline__ int mknod(__const char *, __mode_t, __dev_t);
int main_menu(void);
int option_menu(void);
int color_menu(char *);
int map_type_menu(void);
int arrow_options(void);
int get_arrow_inputs(void);
int arrow_map(void);
/* mk_new_layer.c */
__inline__ int __stat(__const char *, struct stat *);
__inline__ int stat(__const char *, struct stat *);
__inline__ int __lstat(__const char *, struct stat *);
__inline__ int lstat(__const char *, struct stat *);
__inline__ int __fstat(int, struct stat *);
__inline__ int fstat(int, struct stat *);
__inline__ int __mknod(__const char *, __mode_t, __dev_t);
__inline__ int mknod(__const char *, __mode_t, __dev_t);
int make_new_cell_layer(void);
/* mk_tmp_file.c */
__inline__ int __stat(__const char *, struct stat *);
__inline__ int stat(__const char *, struct stat *);
__inline__ int __lstat(__const char *, struct stat *);
__inline__ int lstat(__const char *, struct stat *);
__inline__ int __fstat(int, struct stat *);
__inline__ int fstat(int, struct stat *);
__inline__ int __mknod(__const char *, __mode_t, __dev_t);
__inline__ int mknod(__const char *, __mode_t, __dev_t);
int make_temporary_file(void);
