
MODULE_TOPDIR = ../..

PGM=v.extract

LIBES     = $(VECTLIB) $(VECTLIB_REAL) $(DBMILIB) $(GISLIB)
DEPENDENCIES = $(VECTDEP) $(DBMIDEP) $(GISDEP)
 
include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	

