#define RED                     -1
#define ORANGE          -2
#define YELLOW          -3
#define GREEN           -4
#define BLUE            -5
#define INDIGO          -6
#define VIOLET          -7
#define WHITE           -8
#define BLACK           -9
#define GRAY            -10
int fixed_color[11] ;
int line_color[11] ;
int last_color ;
int current_color ;
