: '%W% %G%'  ${PAINTER?} ${PAINT_DRIVER?}

MAPLP=/dev/ttyb              
BAUD=9600

HRES=101.6
VRES=100.0
NCHARS=80

TEXTSCALE=1.0
TEXTFUDGE=1
TEXTSPACE=2
BLOCKSIZE=35
BLOCKSPACE=5
NBLOCKS=16

export MAPLP BAUD
export HRES VRES NCHARS
export TEXTSCALE TEXTSPACE TEXTFUDGE BLOCKSIZE BLOCKSPACE NBLOCKS

exec ${PAINT_DRIVER?}
