# $Id: Makefile,v 2.0 2000-04-22 10:58:18 markus Exp $

# My make files exploit features of GNU make that other makes
# do not have.  This make file that does nothing
# but tell the user to use GNU make.

# If the user were using GNU make now, this file would not get used because
# GNU make uses a make file named "GNUmakefile" in preference to "Makefile"
# if it exists.

# GNU make utility can be found on ftp://prep.ai.mit.edu/pub/gnu/

all install clean dep depend distclean:
        @echo "You must use GNU make. It may be installed"
        @echo "on your system with the name 'gmake'."

