
MODULE_TOPDIR = ../../..

PGM = g.region
LIBES     = $(VECTLIB) $(GISLIB) $(DATETIMELIB) $(GPROJLIB)  
DEPENDENCIES = $(GISDEP) $(VECTDEP) $(DATETIMEDEP) $(GPROJDEP)
include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




