
MODULE_TOPDIR = ../..

PGM=v.to.rast

LIBES     = $(VECTLIB) $(DBMILIB) $(GISLIB)
DEPENDENCIES = $(VECTDEP) $(RASTERLIB) $(GISDEP)
 
include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	

