: ${PAINTER?} ${PAINT_DRIVER?}
MAPLP=${MAPLP-/dev/$PAINTER}

BAUD=9600

HRES=90.0
VRES=90.0
NCHARS=120

TEXTSCALE=1.0
TEXTFUDGE=0
TEXTSPACE=2
BLOCKSIZE=22
BLOCKSPACE=23
NBLOCKS=20

export MAPLP BAUD
export HRES VRES NCHARS
export TEXTSCALE TEXTSPACE TEXTFUDGE BLOCKSIZE BLOCKSPACE NBLOCKS

exec ${PAINT_DRIVER?}
