.TH pbmtog3 1 "02 October 1989"
.SH NAME
pbmtog3 - convert a portable bitmap into a Group 3 FAX file
.SH SYNOPSIS
.B pbmtog3
.RI [ pbmfile ]
.SH DESCRIPTION
Reads a portable bitmap as output.
Produces a Group 3 FAX file as input.
.SH REFERENCES
The standard for Group 3 FAX is defined in CCITT Recommendation T.4.
.SH "SEE ALSO"
g3topbm(1), pbm(5)
.SH AUTHOR
Copyright (C) 1989 by Paul Haeberli <paul@manray.sgi.com>.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
