/**
 * \file V_error.c
 *
 * \brief Display error functions.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * \author GRASS GIS Development Team
 *
 * \date 1999-2006
 */

#include <grass/config.h>
#include <stdio.h>
#include <unistd.h>
#include <grass/vask.h>


#ifdef __MINGW32__
unsigned int sleep (unsigned int seconds)
{
    /* TODO: no sleep for now */
    return 0;
}
#endif


/**
 * \fn int V_error (char *message)
 *
 * \brief Dispay error routine.
 *
 * Deals with error messages generated by other Visual ask routines.
 *
 * \param[in] message
 * \return always returns 0
 */

int V_error( char *message )
{
	fprintf(stderr,"V_ask error: %s\n", message) ;
	sleep(4) ;

	return 0;
}
