#define	Mem_load_file	dig_Mem_load_file
#define	Mem_release_file	dig_Mem_release_file
#define	Rd_P_area	dig_Rd_P_area
#define	Rd_P_att	dig_Rd_P_att
#define	Rd_P_line	dig_Rd_P_line
#define	Rd_P_node	dig_Rd_P_node
#define	Rd_Plus_head	dig_Rd_Plus_head
#define	Read_line	dig_Read_line
#define	Rewrite_line	dig_Rewrite_line
#define	Wr_P_area	dig_Wr_P_area
#define	Wr_P_att	dig_Wr_P_att
#define	Wr_P_line	dig_Wr_P_line
#define	Wr_P_node	dig_Wr_P_node
#define	Wr_Plus_head	dig_Wr_Plus_head
#define	Write_line	dig_Write_line
#define	_Mem_Read_line	dig__Mem_Read_line
#define	_Read_line	dig__Read_line
#define	_Rewrite_line	dig__Rewrite_line
#define	_Write_line	dig__Write_line
#define	_alloc_space	dig__alloc_space
#define	_falloc	dig__falloc
#define	_frealloc	dig__frealloc
#define	add_line_to_node	dig_add_line_to_node
#define	alloc_area	dig_alloc_area
#define	alloc_att	dig_alloc_att
#define	alloc_line	dig_alloc_line
#define	alloc_node	dig_alloc_node
#define	alloc_points	dig_alloc_points
#define	alloc_space	dig_alloc_space
#define	angle_next_line	dig_angle_next_line
#define	area_alloc_line	dig_area_alloc_line
#define	area_bound_box	dig_area_bound_box
#define	bound_box	dig_bound_box
#define	build_area_with_line	dig_build_area_with_line
#define	calc_begin_angle	dig_calc_begin_angle
#define	calc_end_angle	dig_calc_end_angle
#define	check_nodes	dig_check_nodes
#define	del_area	dig_del_area
#define	del_att	dig_del_att
#define	falloc	dig_falloc
#define	find_area	dig_find_area
#define	frealloc	dig_frealloc
#define	map_to_head	dig_map_to_head
#define	mread	dig_mread
#define	mseek	dig_mseek
#define	mwrite	dig_mwrite
#define	new_area	dig_new_area
#define	new_att	dig_new_att
#define	new_to_old_type	dig_new_to_old_type
#define	node_add_line	dig_node_add_line
#define	node_alloc_line	dig_node_alloc_line
#define	node_color	dig_node_color
#define	node_del_line	dig_node_del_line
#define	old_to_new_type	dig_old_to_new_type
#define	out_of_memory	dig_out_of_memory
#define	prune	dig_prune
#define	read_head_binary	dig_read_head_binary
#define	rmcr	dig_rmcr
#define	snap_line_to_node	dig_snap_line_to_node
#define	struct_copy	dig_struct_copy
#define	update_att	dig_update_att
#define	which_node	dig_which_node
#define	write_areas	dig_write_areas
#define	write_atts	dig_write_atts
#define	write_head_binary	dig_write_head_binary
#define	write_lines	dig_write_lines
#define	write_nodes	dig_write_nodes
#define	write_plus_file	dig_write_plus_file
