.TH GPOLY 1
.SH NAME
Gpoly \- extract areas from cell file into digit file
.SH SYNOPSIS
.B Gpoly
cell_file digit_file
.SH DESCRIPTION
.I Gpoly
scans the named cell_file and extracts lines which will separate it
into areas.

.I Gpoly
will create a vector data file from a given cell file.  It will outline 
each unique area in the cell file and create vector data to represent it.
The cell values will be used to create attribute information for the resultant
vector areas.

.SH BUGS
.I Gpoly
extracts areas only.  If the cell file contains something which
you don't think of as an area, the result may be suprising.

.P
You will need to run 
.I support.vect
on the resultant files to build the dig_plus information.

.SH "SEE ALSO"
\fIsupport.vect[1]\fR

.SH "AUTHOR"
Jean Ezell, U.S. Army Construction Engineering Research Laboratory
