EXTERN struct Cell_head window;
EXTERN char step1[81], step2[81], step3[81], step4[81];
EXTERN char step5[81], step6[81], step7[81], step8[81];
EXTERN char proj_name[41];
EXTERN char elev_name[31],filt_name[31];
EXTERN char river_name[31],aspect_name[31];
EXTERN char lakes_name[31];
EXTERN int filt_num;
EXTERN char *proj_mapset;
EXTERN char *elev_mapset, *filt_mapset;
EXTERN char *river_mapset, *aspect_mapset;
EXTERN char *lakes_mapset;
EXTERN double sl_thres;
EXTERN int pit_thres;
EXTERN double easting, northing;
EXTERN char thin_name[31], *thin_mapset;
EXTERN int acc_thres, thin_num;
EXTERN char extthin_name[31], *extthin_mapset;
EXTERN char clthin_name[31], *clthin_mapset;
EXTERN char basin_name[31], *basin_mapset;
EXTERN int complete[7];
