.TH r.out.tiff 1 "" "" "" ""
.SH NAME
\*Lr.out.tiff\*O  - Converts a GRASS raster file to a 8/24bit TIFF 
image file at the pixel resolution of the CURRENTLY DEFINED REGION.
.br
(GRASS Raster Data Export Program)
.SH SYNOPSIS
\*Lr.out.tiff \*O[\*L-pcv\*O] \*Linput=\*Oname\*O
.SH DESCRIPTION
This program converts a TIFF raster file (8bit) to a GRASS raster file.
Output is placed in the /cell directory
under the user's current GRASS mapset.
.VL 4m
.SH Flags:
.LI "\*L-p\*O
TIFF Pallete output (8bit instead of 24bit).
.LI "\*L-c\*O
Compress with LZW routine.
.LI "\*L-v\*O
Verbose mode
.LE
.SH Parameters:
.VL 4m
.LI "\*Linput=\*Oname
Name of an existing GRASS raster file to be exported. 
.LI "\*Loutput=\*Oname
Name of new TIFF image file. 
.LE
.PP
The program prompts the user to enter the name of the TIFF raster file to be
converted and the name to be assigned to the GRASS raster file
to contain the resultant image. Currently "TIFF/uncompressed", "TIFF/LZW-compression" and TIFF/PackBits-compression" formats are supported.
.PP
The user may adjust region and resolution before export using \*Lg.region\*O
.SH SEE ALSO
\*Lg.region\*O
.SH AUTHOR
Michael Shapiro, U.S.Army Construction Engineering 
Research Laboratory
