
MODULE_TOPDIR = ../../..

PGM = d.mon
LIBES     = $(DISPLAYLIB) $(RASTERLIB) $(VECTLIB) $(DBMILIB) $(GISLIB)
DEPENDENCIES = $(GISDEP) $(VECTDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




