
MODULE_TOPDIR = ..

SUBDIRS = \
	bitmap \
	btree \
	D \
	datetime \
	db \
	display \
	edit \
	external \
	fonts \
	gis \
	image \
	linkm \
	ogsf \
	proj \
	raster \
	vask \
	vector \
	init \
	front.end

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs

clean: cleansubdirs

