MODULE_TOPDIR = ../..

PGM  = r.in.gdal

LIBES= $(GPROJLIB) $(GISLIB) $(IMAGERYLIB) $(GDALLIBS) $(DLLIB)
DEPENDENCIES = $(GPROJDEP) $(GISDEP) $(IMAGERYDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
