.TH i.oif 1 "" "" "" ""
.SH NAME
\*Li.oif\*O - Calculates Optimum Index Factor for LANDSAT TM bands 1,2,3,4,5 and 7
.br
(GRASS shell script) 
.SH SYNOPSIS
\*Li.oif\*O 
.br
\*Li.oif help\*O 
.br
\*Li.oif tm1 tm2 tm3 tm4 tm5 tm7\*O 
.SH DESCRIPTION
i.oif
\*L  Optimum Index factor (OIF)\*O
for all LANDSAT TM band combinations (LANDSAT TM 1,2,3,4,5,7 without termal band 6).
The result is a ranked list, which shows the
information content for all possible combinations (20).
The list is ranked from the best combination down to the 
combination containing less information.
From this the user can derive which band combinations
are interesting to analyse.
Calculation (after CHAVEZ et al. 1984):
\*C
.DS
           Sum of Standard deviations of 3 bands
    OIF = ------------------------------------------------
           Sum of ABS(correlation coefficients of 3 bands)
.DE
\*O
Ref.: Jensen: Introductory digital image processing 1996, p.98
ISBN 0-13-205840-5
.SH AUTHOR
Markus Neteler
.br

University of Hannover, Germany
.br

neteler@geog.uni-hannover.de
