: ${PAINTER?} ${PAINT_DRIVER?}
MAPLP=${MAPLP-/dev/$PAINTER}

BAUD=9600

HRES=120.0
VRES=120.0
NCHARS=80

TEXTSCALE=1.0
TEXTFUDGE=0
TEXTSPACE=2
BLOCKSIZE=35
BLOCKSPACE=25
NBLOCKS=10

export MAPLP BAUD
export HRES VRES NCHARS
export TEXTSCALE TEXTSPACE TEXTFUDGE BLOCKSIZE BLOCKSPACE NBLOCKS

exec ${PAINT_DRIVER?}
