MODULE_TOPDIR = ../../../..

PGM = bmif_to_cell

OBJS=bmf_to_cll.o

LIBES = $(GISLIB)
DEPENDENCIES = $(DEPGISLIB)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

htmlcmd:
	@echo "nothing to do"
