
MODULE_TOPDIR = ..

SUBDIRS = \
	drivers \
	d.erase \
	d.m \
	d.mon \
	d.path \
	d.rast \
	d.vect \
	d.what.rast \
	d.what.vect \
	d.zoom

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs

clean: cleansubdirs

