#!/bin/sh

if test $# != 1; then
    echo Usage: $0 file.xclip
    exit 1
fi

if test ! -f $1; then
    echo No such file: $1 
    echo Usage: $0 file.xclip
    exit 1
fi

echo Installing $1
cp $1 $XGHOME/lib/xclip
