      LOGICAL FUNCTION CHKFIL(FNAME,RW)
      INCLUDE 'syspar.d'
C
C     **UNIX SYSTEM DEPENDENT INTERNAL ROUTINE **
C
C     CHECK FOR A FILE'S EXISTANCE AND READ/WRITE PERMISSION
C
      CHARACTER*(*) FNAME
      LOGICAL RW
C
      INQUIRE(FILE=FNAME,EXIST=RW,IOSTAT=IOS)
      CHKFIL = RW
      RW = .TRUE.
      RETURN
      END
