      SUBROUTINE RIOOPN(FNAME,FILE,NWDS,IOS)
      INCLUDE 'syspar.d'
C
C     *** UNIX SYSTEM DEPENDENT ROUTINE ***
C
C  PURPOSE:   COVER ROUTINE TO OPEN A RANDOM FILE
C
C  PARAMETERS
C         FNAME---NAME OF THE FILE TO OPEN
C         FILE----UNIT TO OPEN
C         NWDS----NUMBER OF WORDS PER RECORD
C         IOS-----STATUS VARIABLE - O MEANS SUCCESS, ELSE TILT
C
      INCLUDE 'rio.d'
      CHARACTER*(*) FNAME
C
C     IGNORE NAMES FOR SCRATCH FILES
      IF (FILE.EQ.ZNSRT1 .OR. FILE.EQ.ZNSRT2) THEN
        OPEN  (UNIT=FILE,           ACCESS='DIRECT',STATUS='SCRATCH',
     .         RECL=NWDS*ZCW,IOSTAT=IOS)
      ELSE
        OPEN  (UNIT=FILE,FILE=FNAME,ACCESS='DIRECT',STATUS='UNKNOWN',
     .         RECL=NWDS*ZCW,IOSTAT=IOS)
      ENDIF
      IF (IOS.NE.0) WRITE(6,1000) IOS, FILE,FNAME
1000  FORMAT(' RIOOPN: ',I4,I4,2X,A)
 
      IUN = FILE - ZNFIL1 + 1
      IRECPS(IUN) = 1
      RETURN
      END
