      SUBROUTINE RMTIME(TIM)
      INCLUDE 'syspar.d'
C
C     ***UNIX SYSTEM DEPENDENT ROUTINE ***
C
C  PURPOSE:   RETURN THE CURRENT TIME AS INTEGER (SEC FROM MIDNIGHT)
C
C  PARAMETERS:
C         TIM-----THE CURRENT TIME
C
      CALL CZTIME(H,M,S)
      TIM = H*3600 + M*60 + S
      RETURN
      END
