/* dig_curses.c */
int Init_curses(void);
int Close_curses(void);
int _Write_base_win(void);
int Write_base_win(void);
int _write_generic_title(char *);
int Dig_menu_opts(void);
int _Write_mouse_covr(void);
int _Write_dig_win(void);
int Write_dig_win(void);
int _Write_header_info(void);
int Write_header_info(void);
int _Write_type_info(void);
int Write_type_info(void);
int _Write_base(int, char *);
int _Base_string(int, int, char *);
int Base_string(int, int, char *);
int Write_base(int, char *);
int _Write_info(int, char *);
int Write_info(int, char *);
int Clear_help(void);
int _Clear_help(void);
int Clear_base(void);
int _Clear_base(void);
int Clear_info(void);
int _Clear_info(void);
int Replot_screen(void);
int Get_curses_char(char *);
int Get_curses_text(char []);
int _show_mode(int, int, int);
int show_mode(int, int, int);
int _Base_refresh(void);
int curses_yes_no(int, char *);
int curses_yes_no_default(int, char *, int);
int mysuspend(void);
int myrespend(void);
int vask_suspend(void);
int vask_respend(void);
int get_type_cnt(int);
int _Write_help(int, char *);
int _Help_string(int, int, char *);
int Help_string(int, int, char *);
int Write_help(int, char *);
int Show_help(void);
int Hide_help(void);
int _Info_refresh(void);
int _Help_refresh(void);
int help_get_key(void);
int _Curses_on(void);
int _Curses_off(void);
int Curses_state(void);
int curses_getchar(void);
int _Write_covr(int, char *);
int _Covr_string(int, int, char *);
int Covr_string(int, int, char *);
int Write_covr(int, char *);
int Clear_covr(void);
int _Clear_covr(void);
int _Covr_refresh(void);
int _Show_version(void);
int Curses_error(char *);
int make_dig_win(char [16][80]);
