int Del_area(struct Map_info *, int);
int _Del_area(struct Map_info *, int);
int unfinished_areas(struct Map_info *);
int break_line(struct Map_info *);
int break_line_w_point(struct Map_info *, int, double, double);
int build_neat(struct Map_info *);
int build_area(struct Map_info *,double,double,int,P_AREA *);
int color_setup(struct Map_info *);
int compress(struct Map_info *, int);
int label_contour(struct Map_info *, int);
int Custom_settings(struct Map_info *);
int do_digitize(struct Map_info *, int, int, double, int, int);
int last_words(struct Map_info *, int);
int do_file_checks(struct Map_info *);
int display_duplicate_lines(struct Map_info *);
int init_plus(struct Map_info *);
int Del_isle(struct Map_info *, int);
int label_area(struct Map_info *, int);
int label_lines(struct Map_info *, int);
int label_sites(struct Map_info *, int);
int label_line(struct Map_info *, int, int, struct line_pnts *);
int init_plus (struct Map_info *);
int unlabel_area(struct Map_info *);
int unlabel_lines(struct Map_info *);
int unlabel_sites(struct Map_info *);
int tell_line_label(struct Map_info *, int);
int make_area_label(struct Map_info *, int);
int tell_area_unlabel(struct Map_info *, int);
int tell_area_label(struct Map_info *, int);
int check_area(struct Map_info *, int, double, double);
int display_labeled_areas(struct Map_info *);
int display_all_areas(struct Map_info *);
int display_labeled_lines(struct Map_info *);
int display_unlabeled_lines(struct Map_info *);
int label_all_lines(struct Map_info *, int);
int label_mlines(struct Map_info *, int);
int check_scale(struct Map_info *);
int move_line(struct Map_info *);
int move_point(struct Map_info *);
int new_line(struct Map_info *, int, struct new_node *, struct line_pnts *);
int node_lines(struct Map_info *);
int plot_overlay(struct Map_info *);
int free_name_info(struct Map_info *);
int remove_line(struct Map_info *, int);
int _remove_line(struct Map_info *, int);
int __remove_line(struct Map_info *, int);
int remove_block(struct Map_info *);
int replot(struct Map_info *);
int display_nodes(struct Map_info *);
int display_all_lines(struct Map_info *);
int display_tlines(struct Map_info *, int);
int reset_map(struct Map_info *, char *);
int retype_line(struct Map_info *);
int check_next(struct Map_info *, int, int);
int reset_snap_thresh(struct Map_info *);
int reset_thresh(struct Map_info *);
int snap_nodes(struct Map_info *);
int smooth_line(struct Map_info *);
int angle_in_line(struct Map_info *, int);
int where_am_i(struct Map_info *);
int display_cents(struct Map_info *);
int display_alabels(struct Map_info *);
int highlight_llabel(struct Map_info *, int);
int display_llabel(struct Map_info *, int);
int display_llabels(struct Map_info *);
int display_llines(struct Map_info *);
int display_lareas(struct Map_info *);
int display_unlabeled_areas(struct Map_info *);
int display_islands(struct Map_info *);
int window_setup(struct Map_info *);
int within_a_thresh(struct Map_info *);
int _line_really_in_window (struct Map_info *,
     P_LINE *,double,double,double,double );
