#!/bin/sh
# the next line restarts using tclsh \
exec $GRASS_TCLSH "$0" "$@"

global env
global argv

#set ENV for script
set NVIZ_SCRIPTS $env(GISBASE)/etc/nviz2.2/scripts

set env(GISDBASE) [exec g.gisenv get=GISDBASE]
set env(LOCATION_NAME) [exec g.gisenv get=LOCATION_NAME]
set env(MAPSET) [exec g.gisenv get=MAPSET]

#Execute Command
if {$argv == ""} {
#no arguments 
eval exec $env(GISBASE)/etc/nviz2.2/NVWISH2.2 -f $env(GISBASE)/etc/nviz2.2/scripts/nviz2.2_script -name NVIZ >&@stdout
} else {
#pass arguments
eval exec $env(GISBASE)/etc/nviz2.2/NVWISH2.2 -f $env(GISBASE)/etc/nviz2.2/scripts/nviz2.2_script $argv -name NVIZ >&@stdout
}
