.TH nviz 1 "26 June 1995"
.SH NAME
nviz \- Visualization and animation tool for GRASS data
.br
.SH SYNOPSIS
.B nviz
.br
.B nviz
[
.B \-q
]
[
.BI path= dir
]
[
.BI elevation= name
[
,name,...
]
]
.RS 5
[
.BI vector= name
[
,name,...
]
]
.RS 0
[
.BI sites= name
[
,name,...
]
]

.SH DESCRIPTION
.LP
\fBnviz\fR organizes several useful tools for combining and
visualizing GRASS raster, vector and site files.  In particular,
\fBnviz\fR provides a detailed user interface with several panels used
for specifying various options.  The user may specify arbitrary
combinations of raster maps, vector maps, and site maps.  The
attributes associated with each map (such as color, masking, line
width, etc.) may be modified independently.  Also, cut-planes may be
used to display an interpolated cross section of a set of raster maps.
\fBnviz\fR emphasizes a flexible and natural viewing mechanism
allowing the user to modify view parameters such as camera position,
surface exaggeration, display resolution, lighting models, and light
position.  Lastly, \fBnviz\fR supports an animation and scripting
mechanism for building visualizations of sequences of GRASS data.  The
scripting mechanism may be used to record and playback any user
session.  Other miscellaneous features include: a facility for
querying map displays for information, and image processing tools
which allow the placement of labels and scales on the display.
.LP

.SH OPTIONS

The initial set of files used by
.B nviz
may be specified by providing file arguments for \fIelevation\fR,
\fIvector\fR and \fIsites\fR.  If the user specifies program arguments
on the command line, the program will start with the given set of
files.  Alternatively, the user can simply type \fBnviz\fR on the
command line and the program will ask for parameter values and flag
settings interactively, using the standard GRASS parser interface.

.LP 
\fBFlags:\fR 
.IP \fB-q\fR 10
Quickstart.  Skip over the usual GRASS parser interface and start
\fBnviz\fR.  Ignores any file parameters which may have been specified
on the command line.

.LP
\fBParameters:\fR

.IP \fBpath\fR=\fIdir\fR 30
Search for additional panels in the specified directory.

.IP \fBelevation\fR=\fIname[,name,...]\fR  30
Use the given list of existing raster files as input.

.IP \fBvector\fR=\fIname[,name,...]\fR 30
Use the given list of existing vector files as input.

.IP \fBsites\fR=\fIname[,name,...]\fR 30
Use the given list of existing sites files as input.

.SH NOTES

Currently, \fBnviz\fR must be invoked from within GRASS (preferably
version 4.2).  That is, start GRASS then invoke \fBnviz\fR from the
GRASS shell.
.LP
\fBnviz\fR is built on top of the Tcl/Tk environment.  Be sure you
have at least Tcl 7.3 or later and Tk 3.6 or later and that
appropriate environment variables are set correctly.
.LP

.SH DIAGNOSTICS
.TP
ERROR: LOCATION_NAME not set
The program was run outside of GRASS.
.LP
Tcl_AppInit failed: can't find /usr/local/lib/tcl/init.tcl; perhaps you need to
install Tcl or set your TCL_LIBRARY environment variable?
.RS
Tcl not installed correctly or TCL_LIBRARY environment variable not
set correctly.
.RE
.LP
Tcl_AppInit failed: can't find /usr/local/lib/tk/tk.tcl; perhaps you need to
install Tk or set your TK_LIBRARY environment variable?
.RS
Tk not installed correctly or TK_LIBRARY environment variable not set
correctly.
.RE
.LP
Usage:
 nviz [-q] [elevation=name[,name,...]] 
.RS
  [vector=name[,name,...]]
.RS 0
  [sites=name[,name,...]]
.br
Invalid options were specified on the command line.
.RE
.LP

.SH "SEE ALSO"
.I "sg3d, Nviz"
.SH AUTHORS
.SS Original program (Sg3d(NASA Panels) and Nviz(Motif) versions):
.br
David Gerdes, Bill Brown, and Helena Mitasova, US Army CERL.
.SS  Current version (Tcl/Tk version):
.br
Bill Brown, David Gerdes, Helena Mitasova, Terry Baker, and Mark
Astley, US Army CERL.  Various members of the GRASS community have
provided suggestions throughout the duration of the project.
.br

