int x_sqrt(int, double *[], register double *, register int);
int n_sqrt(int, char *);
int n_exp(int, char *);
int x_exp(int, double *[], double *, int);
int x_log(int, double *[], double *, int);
int n_log(int, char *);
int x_cos(int, double *[], register double *, register int);
int n_cos(int, char *);
int x_sin(int, double *[], register double *, register int);
int n_sin(int, char *);
int x_tan(int, double *[], register double *, register int);
int n_tan(int, char *);
int x_atan(int, double *[], register double *, register int);
int n_atan(int, char *);
int i_abs(int, CELL *[], register CELL *, register int);
int x_abs(int, double *[], register double *, register int);
int n_abs(int, char *);
int i_if(int, CELL *[], register CELL *, register int);
int x_if(int, double *[], register double *, register int);
int n_if(int, char *);
int i_max(int, CELL *[], register CELL *, register int);
int x_max(int, double *[], register double *, register int);
int n_max(int, char *);
int i_median(int, CELL *[], register CELL *, register int);
int x_median(int, double *[], register double *, int);
int n_median(int, char *);
int i_min(int, CELL *[], register CELL *, register int);
int x_min(int, double *[], register double *, register int);
int n_min(int, char *);
int i_mode(int, CELL *[], register CELL *, register int);
int x_mode(int, double *[], register double *, register int);
int n_mode(int, char *);
int i_round(int, CELL *[], register CELL *, register int);
int x_round(int, double *[], register CELL *, register int);
int n_round(int, char *);
int x_2float(int, double *[], register double *, register int);
int n_2float(int, char *);
int i_2int(int, CELL *[], register CELL *, register int);
int x_2int(int, double *[], register CELL *, register int);
int n_2int(int, char *);
int i_eval(int, CELL *[], register CELL *, register int);
int x_eval(int, double *[], register double *, int);
int n_eval(int, char *);
int i_rand(int, CELL *[], register CELL *, register int);
int x_rand(int, double *[], register double *, register int);
int n_rand(int, char *);
int i_row(int, CELL *[], register CELL *, register int);
int n_row(int, char *);
int i_col(int, CELL *[], register CELL *, register int);
int n_col(int, char *);
int x_x(int, double *[], register double *, register int);
int n_x(int, char *);
int x_y(int, double *[], register double *, register int);
int n_y(int, char *);
int x_ewres(int, double *[], register double *, register int);
int n_ewres(int, char *);
int x_nsres(int, double *[], register double *, register int);
int n_nsres(int, char *);
int i_null(int, CELL *[], register CELL *, register int);
int x_null(int, double *[], register double *, register int);
int n_null(int, char *);
int i_isnull(int, CELL *[], register CELL *, register int);
int x_isnull(int, double *[], register CELL *, register int);
int n_isnull(int, char *);
