/***********************************************************************

NAME:		V_error()

FUNCTION:	Deals with error messages generated by other Visual ask 
			routines.

USAGE:		V_error(message)

PARAMETERS:
			char *message ;

RETURNS:	zero (0) 

ALGORITHM:	
		|	Print the message to standard error

CALLS:		

***********************************************************************/

#include <stdio.h>
V_error(message)
	char *message ;
{
	fprintf(stderr,"V_ask error: %s\n", message) ;
	sleep(4) ;
}
