
MODULE_TOPDIR = ../..

PGM = d.zoom
LIBES     = $(DISPLAYLIB) $(RASTERLIB) $(VECTLIB) $(GISLIB) $(DATETIMELIB) 
DEPENDENCIES = $(VECTDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




