MODULE_TOPDIR = ../..

PGM = r.out.tiff
EXTRA_CFLAGS = $(TIFFINCPATH) $(TIFFLIBPATH)

LIBES = $(GISLIB) $(TIFFLIB)
DEPENDENCIES = $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
