#include "gis.h"
#include "parms.h"

gen_labels (fd, parms, cats, colr, range, window, cellname, mapset)
    FILE *fd;
    struct parms *parms;
    struct Categories *cats;
    struct Colors *colr;
    struct Range *range;
    struct Cell_head *window;
    char *cellname, *mapset;
{
    long count;
    int len;
    int maxlen;
    int need_space;
    int red,grn,blu;
    double r,g,b;
    CELL cp;
    char *label;
    char *title;
    double window_width, window_height, start;
    double legend_height, legend_start;
    double text_height, text_space;
    double fill;
    double north;
    double xref, yref;

    fprintf (fd,"# Generated by %s\n", G_program_name());
    fprintf (fd,"# Map layer: %s in %s\n", cellname, mapset);
    fprintf (fd,"# Window\n");
    fprintf (fd,"#   north: %12.2lf   east: %12.2lf\n",
	window->north, window->east);
    fprintf (fd,"#   south: %12.2lf   west: %12.2lf\n",
	window->south, window->west);
    fprintf (fd,"# Legend\n");
    fprintf (fd,"#   %-52s %8.2lf\n",
	"height (as percent of window):", parms->height);
    fprintf (fd,"#   %-52s %8.2lf\n",
	"inter-label spacing (as percent of text height):", parms->space);
    fprintf (fd,"#   %-52s %8.2lf\n",
	"vertical reference (as percent of window):", parms->yref);
    fprintf (fd,"#   %-52s %8.2lf\n",
	"horizontal reference (as percent of window):", parms->xref);
    fprintf (fd,"#   %-52s ","reference position:");
    switch (*parms->ref)
    {
    case 'c': fprintf (fd, "%8s\n","center"); break;
    case 't': fprintf (fd, "%8s\n","top"); break;
    default:  fprintf (fd, "%8s\n","bottom"); break;
    }
    fprintf (fd, "\n# DO NOT MODIFY THIS FILE\n\n");


/* count the number of labels */
    maxlen = 0;
    count = 0;
    for (cp = range->nmin; cp <= range->nmax; cp++)
    {
	if (cp == 0) continue;
	label = G_get_cat (cp, cats);
	if(len = strlen (label))
	{
	    len += 2;
	    count++;
	    if (len > maxlen)
		maxlen = len;
	}
    }
    for (cp = range->pmin; cp <= range->pmax; cp++)
    {
	if (cp == 0) continue;
	label = G_get_cat (cp, cats);
	if(len = strlen (label))
	{
	    len += 2;
	    count++;
	    if (len > maxlen)
		maxlen = len;
	}
    }
    if (count == 0)
    {	
	G_warning ("No labels found in category file");
	return;
    }
    title = G_get_cats_title (cats);
    if (*title)
    {
	len = strlen (title);
	if (len > maxlen)
	    maxlen = len;
	count++;
    }

/* convert percents to mutiplier */
    parms->height /= 100.0;
    parms->space  /= 100.0;
    parms->xref   /= 100.0;
    parms->yref   /= 100.0;

/* compute legend height and reference lenghts */
    window_width  = window->east  - window->west;
    window_height = window->north - window->south;
    legend_height = window_height * parms->height ;
    xref          = window->west  + window_width * parms->xref ;
    yref          = window->north - window_height * parms->yref ;

/* to compute text height, use formula: legend_height = H*count+S*(count-1)
 * where H is text height, S is inter label spacing, with S=H*s,
 * where s is percent of text height:
 *
 *   legend_height = H*count + H*s*(count-1)
 *
 * solve for H:
 * 
 *        H = legend_height / (count + s*(count-1))
 *
 * then compute S:
 *
 *        S = H * s
 */

    text_height = legend_height / ( count + (count-1) * parms->space);
    text_space  = text_height * parms->space ;

    fprintf (fd, "# window height:  %lf\n", window_height);
    fprintf (fd, "# window width:   %lf\n", window_width);
    fprintf (fd, "# legend height:  %lf\n", legend_height);
    fprintf (fd, "# vertical ref:   %lf\n", yref);
    fprintf (fd, "# horizontal ref: %lf\n", xref);
    fprintf (fd, "# text_height:    %lf\n", text_height);
    fprintf (fd, "# text_space:     %lf\n", text_space);
    fprintf (fd, "# count:          %ld\n", (long)count);
    fprintf (fd, "opaque: yes\n");
    fprintf (fd, "size: %lf\n", text_height);
    fprintf (fd, "ref: lower left\n");

/* compute start northing of legend */
    switch (*parms->ref)
    {
    case 't':
	legend_start = yref ;
	break;
    case 'c':
	legend_start = yref - (legend_height + text_height)/2;
	break;
    default:
	legend_start = yref - (legend_height + text_height);
	break;
    }
/* if bottom of legend is too far south, move it to the southern edge */
    if ((legend_start - (legend_height + text_height)) < window->south)
	legend_start = window->south + legend_height + text_height;
/* if top of legend is too far north, move it to the northern edge */
    if (legend_start > window->north)
	legend_start = window->north;

/* generate enough white labels on white background to simulate
 * a white background for all the labels
 */
    north = legend_start;
    fill = legend_height + text_height;

    fprintf (fd, "# legend background\n\n");
    fprintf (fd, "color: white\n");
    fprintf (fd, "background: white\n");
    fprintf (fd, "border: none\n");
    fprintf (fd, "east: %lf\n", xref);

    while (fill >= text_height)
    {
	north -= text_height;
	fill  -= text_height;
	fprintf (fd, "north: %lf\n", north);
	fprintf (fd, "text: ");
	for (len = 0; len < maxlen; len++)
	    fprintf (fd, "W");
	fprintf (fd, "\n");
    }
    if (fill)
    {
	north -= fill;
	fprintf (fd, "north: %lf\n", north);
	fprintf (fd, "text: ");
	for (len = 0; len < maxlen; len++)
	    fprintf (fd, "W");
	fprintf (fd, "\n");
    }

/* generate the labels */

    fprintf (fd, "\n# the labels\n\n");
    north = legend_start - text_height/2;

    fprintf (fd, "color: black\n");
    fprintf (fd, "background: none\n");
    need_space = 0;
    if (*title)
    {
	north -= text_height;
	fprintf (fd, "east: %lf\n", xref + text_height/2);
	fprintf (fd, "north: %lf\n", north);
	fprintf (fd, "text:%s\n", title);
	need_space = 1;
    }
    fprintf (fd, "east: %lf\n", xref + text_height*2);
    for (cp = range->nmin; cp <= range->nmax; cp++)
    {
	if (cp == 0) continue;
	label = G_get_cat (cp, cats);
	if (*label)
	{
	    north -= text_height;
	    if (need_space)
		north -= text_space;
	    fprintf (fd, "north: %lf\n", north);
	    fprintf (fd, "text:%s\n", label);
	    need_space = 1;
	}
    }
    for (cp = range->pmin; cp <= range->pmax; cp++)
    {
	if (cp == 0) continue;
	label = G_get_cat (cp, cats);
	if (*label)
	{
	    north -= text_height;
	    if (need_space)
		north -= text_space;
	    fprintf (fd, "north: %lf\n", north);
	    fprintf (fd, "text:%s\n", label);
	    need_space = 1;
	}
    }

/* generate the color boxes */

    fprintf (fd, "\n# the color boxes\n\n");
    north = legend_start - text_height/2;

    fprintf (fd, "border: black\n");
    fprintf (fd, "east: %lf\n", xref + text_height/2);
    need_space = 0;
    if (*title)
    {
	north -= text_height;
	need_space = 1;
    }
    for (cp = range->nmin; cp <= range->nmax; cp++)
    {
	if (cp == 0) continue;
	label = G_get_cat (cp, cats);
	if (*label)
	{
	    north -= text_height;
	    if (need_space)
		north -= text_space;
	    G_get_color (cp, &red, &grn, &blu, colr);
	    r = red/255.0;
	    g = grn/255.0;
	    b = blu/255.0;
	    fprintf (fd, "color: %lf %lf %lf\n", r, g, b);
	    fprintf (fd, "background: %lf %lf %lf\n", r, g, b);
	    fprintf (fd, "north: %lf\n", north);
	    fprintf (fd, "text:W\n");
	    need_space = 1;
	}
    }
    for (cp = range->pmin; cp <= range->pmax; cp++)
    {
	if (cp == 0) continue;
	label = G_get_cat (cp, cats);
	if (*label)
	{
	    north -= text_height;
	    if (need_space)
		north -= text_space;
	    G_get_color (cp, &red, &grn, &blu, colr);
	    r = red/255.0;
	    g = grn/255.0;
	    b = blu/255.0;
	    fprintf (fd, "color: %lf %lf %lf\n", r, g, b);
	    fprintf (fd, "background: %lf %lf %lf\n", r, g, b);
	    fprintf (fd, "north: %lf\n", north);
	    fprintf (fd, "text:W\n");
	    need_space = 1;
	}
    }
}
