C ROUTINES TO OPEN THE FORTRAN I/O UNITS USED BY THE CALCOMP UHCBS
C YOU NEED TO SET "FILE" IN THE OPEN COMMAND BELOW TO THE ACTUAL
C DEVICE NAME USED ON YOUR SYSTEM
C
      SUBROUTINE POPEN (IUNIT)  
      OPEN (IUNIT,FILE='/dev/tty00',FORM='FORMATTED',ACCESS='SEQUENTIAL'
     1      ,STATUS='UNKNOWN')
      RETURN
      END
   
      SUBROUTINE PCLOSE (IUNIT)
      CLOSE (IUNIT)
      RETURN
      END

