      FUNCTION ASCAN(STRING,SC,NC,ACHR,COMP)
      INCLUDE 'syspar.d'
C
C     LOOKS FOR ACHR IN STRING FROM SC FOR NC CHARACTERS
C     STRING IS ASCII-TEXT
C     NC<0 MEANS SCAN RIGHT TO LEFT
C
C     STRING....ASCII-TEXT TO SCAN
C     SC .......LEFTMOST CHARACTER TO CHECK
C     NC .......NUMBER OF CHARACTERS
C     ACHR......ASCII-CHAR TO LOOK FOR
C     COMP......TRUE TO LOOK FOR CHAR EQUAL
C               FALSE TO LOOK FOR CHAR NOT EQUAL
C
      LOGICAL COMP
 
      IF (NC.EQ.0) GOTO 110
      IF (NC.GT.0) THEN
         ST = SC
         EN = ST + NC - 1
         IC = 1
      ELSE
         ST = SC - NC - 1
         EN = SC
         IC = -1
      ENDIF
C
      DO 100 I = ST,EN,IC
      CALL GETT(STRING,I,TCHR)
      ASCAN = I
      IF (COMP .AND. TCHR.EQ.ACHR) GOTO 200
      IF ((.NOT.COMP) .AND. TCHR.NE.ACHR) GOTO 200
100   CONTINUE
110   ASCAN = 0
200   CONTINUE
      END
