      SUBROUTINE ATTDEL(STATUS)
      INCLUDE 'syspar.d'
C
C  PURPOSE:   DELETE THE CURRENT TUPLE FROM THE ATTRIBUTE RELATION
C             BASED ON CONDITIONS SET UP IN LOCATT AND ATTGET
C
C  PARAMETERS:
C         STATUS--STATUS VARIABLE - 0 MEANS OK, 1 MEANS NO WAY
      INCLUDE 'rmatts.d'
      INCLUDE 'attble.d'
      INCLUDE 'start.d'
C
      STATUS = 0
      IF(LROW.EQ.0) GO TO 9000
C
C  CHANGE THE TUPLE STATUS FLAG TO DELETED.
C
      ATTBLE(1,LROW) = -ATTBLE(1,LROW)
      ATTMOD = 1
      GO TO 9999
C
C  UNABLE TO FIND WHAT WE ARE LOOKING FOR.
C
 9000 CONTINUE
      STATUS = 1
 9999 CONTINUE
      RETURN
      END
