      SUBROUTINE BLKEXT(IND,NROWS,NCOLS)
      INCLUDE 'syspar.d'
C
C  PURPOSE:    EXTRACT THE NUMBER OF ROWS AND COLUMNS FOR A BLOCK
C
C  PARAMETERS
C     INPUT:   IND-----BLOCK INDEX
C     OUTPUT:  NROWS---NUMBER OF ROWS
C              NCOLS---NUMBER OF COLUMNS
      INCLUDE 'incore.d'
C
C  EXTRACT THE DATA FROM BLOCKS.
C
      NROWS = BLOCKS(2,IND)
      NCOLS = BLOCKS(3,IND)
      RETURN
      END
