      SUBROUTINE BLKMOV(TO,FROM,NWORDS)
      INCLUDE 'syspar.d'
C
C  PURPOSE:   MOVE WORDS BETWEEN ARRAYS
C
      INTEGER TO(1),FROM(1)
      IF(NWORDS.LT.0) GO TO 200
C
C  MOVE FROM THE FRONT OF THE ARRAYS.
C
      DO 100 I=1,NWORDS
      TO(I) = FROM(I)
  100 CONTINUE
      RETURN
C
C  MOVE FROM THE REAR OF THE ARRAYS.
C
  200 CONTINUE
      NW = -NWORDS
      DO 300 I=1,NW
      TO(NW+1-I) = FROM(NW+1-I)
  300 CONTINUE
      RETURN
      END
