      SUBROUTINE F1CLO
      INCLUDE 'syspar.d'
C
C  PURPOSE:   CLOSE THE RIM DIRECTORY FILE - FILE 1
C
      INCLUDE 'ascpar.d'
      INCLUDE 'f1com.d'
      INCLUDE 'rimcom.d'
      INCLUDE 'attble.d'
      INCLUDE 'reltbl.d'
      INCLUDE 'lnktbl.d'
      INCLUDE 'flags.d'
      COMMON /USAGE/ CPTTD,CPSTRT,KUSAGE(20)
      INCLUDE 'dstats.d'
C
C  WRITE OUT THE RELATION BUFFER IF IT WAS MODIFIED.
C
      IF(RELMOD.EQ.0) GO TO 100
      CALL RIOOUT(FILE1,CRREC,RELBUF,LENBF1,IOS)
      IF(IOS.NE.0) RMSTAT = 2100 + IOS
  100 CONTINUE
      CRREC = 0
      RELMOD = 0
C
C  WRITE OUT THE ATTRIBUTE BUFFER IF IT WAS MODIFIED.
C
      IF(ATTMOD.EQ.0) GO TO 200
      CALL RIOOUT(FILE1,CAREC,ATTBUF,LENBF1,IOS)
      IF(IOS.NE.0) RMSTAT = 2100 + IOS
  200 CONTINUE
      CAREC = 0
      ATTMOD = 0
C
C  WRITE OUT THE LINK BUFFER IF IT WAS MODIFIED.
C
      IF(LNKMOD.EQ.0) GO TO 300
      CALL RIOOUT(FILE1,CLREC,LNKBUF,LENBF1,IOS)
      IF(IOS.NE.0) RMSTAT = 2100 + IOS
  300 CONTINUE
      CLREC = 0
      LNKMOD = 0
C
C  ZERO OUT RELBUF AND MOVE CONTROL VARIABLES THERE.
C
      CALL ZEROIT(RELBUF,LENBF1)
      CALL ZMOVE(RELBUF(ZFXHDB),DBNAME)
      CALL ZMOVE(RELBUF(ZFXHID),KDBHDR)
      CALL ZMOVE(RELBUF(ZFXHOW),OWNER )
      RELBUF(ZFXHVS) = KDBVER
      RELBUF(ZFXHDT) = DBDATE
      RELBUF(ZFXHTM) = DBTIME
      RELBUF(ZF1HLR) = LF1REC
      RELBUF(ZF1HNR) = NRROW
      RELBUF(ZF1HNA) = NAROW
      RELBUF(ZF1HNL) = NLROW
CCCCDCRELBUF(ZF1HDR+1)=IFIX((CPTTD+SECOND()-CPSTRT)*100)
      CALL BLKMOV(RELBUF(ZF1HDR+2),KUSAGE,20)
CC    RELBUF(51) = ISTAT
CC    RELBUF(52) = INT(CPLAST*100.)
CC    RELBUF(53) = IDELP
C
C  WRITE OUT THE CONTROL BLOCK.
C
      CALL RIOOUT(FILE1,1,RELBUF,LENBF1,IOS)
CCC   CALL BLKDSP('F1CLOSE',RELBUF, 'ZIZZIIIII')
      IF(IOS.NE.0) RMSTAT = 2100 + IOS
C
C     SYSTEM DEPENDENT CLOSE ROUTINE
C
      CALL RIOCLO(FILE1)
      RETURN
      END
