      SUBROUTINE LNKPUT(STATUS)
      INCLUDE 'syspar.d'
C
C     REPLACE THE CURRENT LINK TUPLE INTO /LNKTBL/
C
C         STATUS--STATUS VARIABLE - 0 MEANS OK, 1 MEANS NO WAY
 
      INCLUDE 'flags.d'
      INCLUDE 'tuplel.d'
      INCLUDE 'lnktbl.d'
C
      STATUS = 0
      IF(LLROW.EQ.0) GO TO 9000
C
C  MOVE THE STUFF TO ROW LLROW.
C
      CALL ZMOVE(LNKTBL(ZL2,LLROW),LNAME)
      CALL ZMOVE(LNKTBL(ZL3,LLROW),R1NAME)
      CALL ZMOVE(LNKTBL(ZL4,LLROW),A1NAME)
      CALL ZMOVE(LNKTBL(ZL5,LLROW),R2NAME)
      CALL ZMOVE(LNKTBL(ZL6,LLROW),A2NAME)
      LNKMOD = 1
      IFMOD = .TRUE.
      GO TO 9999
C
C  UNABLE TO FIND WHAT WE ARE LOOKING FOR.
C
 9000 CONTINUE
      STATUS = 1
 9999 CONTINUE
      RETURN
      END
