      FUNCTION LOCASE(ASCHR)
      INCLUDE 'syspar.d'
C
C     RETURN THE LOWER CASE EQUIVALENT OF ASCHR (ASCII-CHAR)
C
      PARAMETER (UA=65,UZ=90,OFF=97-65)
C
C
      IF (ASCHR.LT.UA .OR. ASCHR.GT.UZ) THEN
         LOCASE = ASCHR
      ELSE
         LOCASE = ASCHR + OFF
      ENDIF
      RETURN
      END
