      FUNCTION LOCATT(ANAME,RNAME)
      INCLUDE 'syspar.d'
C
C  PURPOSE:   LOOK FOR ATTRIBUTES AND RELATIONS IN THE ATTRIBUTE
C             RELATION
C
C  PARAMETERS:
C         ANAME---NAME OF ATTRIBUTE OR BLANKS
C         RNAME---NAME OF RELATION OR BLANKS
C         LOCATT--STATUS VARIABLE - 0 MEANS OK, 1 MEANS NO WAY
      INCLUDE 'attble.d'
      INCLUDE 'start.d'
      INCLUDE 'ascpar.d'
      LOGICAL EQ
      LOGICAL NE
      INCLUDE 'dclar1.d'
      LOCATT = 0
C
C  SEE WHAT THE CALLER WANTS.
C
      IF(EQ(RNAME,BLANK)) GO TO 1000
C
C  RNAME IS SPECIFIED.
C
C
C  FIND THE START FOR THIS RELATION.
C
C
C  GET THE PAGE WITH THE DATA FOR THIS RELATION.
C
  100 CONTINUE
      CALL ZMOVE(CRNAME,RNAME)
      MRSTRT = ZATTRI
  200 CONTINUE
      CALL ATTPAG(MRSTRT)
C
C  LOOK FOR THE ATTRIBUTE IN THIS RELATION.
C
      I = MRSTRT
  300 CONTINUE
      IF(I.GT.APBUF) GO TO 400
      IF(ATTBLE(ZA1,I).LT.0) GO TO 350
CC    CALL MSG(' ','  LOCATT: (REL): ','+')
CC    CALL AMSG(RNAME,ZC,'+')
CC    CALL AMSG(ATTBLE(ZA3,I),ZC,' ')
      IF(NE(ATTBLE(ZA3,I),RNAME)) GO TO 350
      IF(EQ(ANAME,BLANK)) GO TO 500
CC    CALL MSG(' ','  LOCATT: (ATT): ','+')
CC    CALL AMSG(ANAME,ZC,'+')
CC    CALL AMSG(ATTBLE(ZA2,I),ZC,' ')
      IF(EQ(ATTBLE(ZA2,I),ANAME)) GO TO 500
  350 CONTINUE
      IF(ATTBLE(ZA1,I).EQ.0) GO TO 400
      I = I + 1
      GO TO 300
C
C  GET THE NEXT PAGE.
C
  400 CONTINUE
      MRSTRT = ATTBUF(1)
      IF(MRSTRT.EQ.0) GO TO 9000
      GO TO 200
C
C  WE FOUND THE ROW WE ARE LOOKING FOR.
C
  500 CONTINUE
      CALL ZMOVE(CANAME,ANAME)
      CROW = I
      LROW = 0
      GO TO 9999
C
C  SCAN FOR ATTRIBUTE WITHOUT RELATION SPECIFIED.
C
 1000 CONTINUE
      IF(EQ(ANAME,BLANK)) GO TO 9000
      MRSTRT = ZATTRI
 1100 CONTINUE
      CALL ATTPAG(MRSTRT)
      I = MRSTRT
 1200 CONTINUE
      IF(I.GT.APBUF) GO TO 1400
      IF(ATTBLE(ZA1,I).LT.0) GO TO 1300
CC    CALL MSG(' ','  LOCATT: (NO RELATION): ','+')
CC    CALL AMSG(ANAME,ZC,'+')
CC    CALL AMSG(ATTBLE(ZA2,I),ZC,' ')
      IF(EQ(ATTBLE(ZA2,I),ANAME)) GO TO 1500
 1300 CONTINUE
      IF(ATTBLE(ZA1,I).EQ.0) GO TO 1400
      I = I + 1
      GO TO 1200
C
C  GET THE NEXT PAGE.
C
 1400 CONTINUE
      MRSTRT = ATTBUF(1)
      IF(MRSTRT.EQ.0) GO TO 9000
      GO TO 1100
C
C  FOUND IT.
C
 1500 CONTINUE
      CALL ZMOVE(CRNAME,BLANK)
      CALL ZMOVE(CANAME,ANAME)
      CROW = I
      LROW = 0
      GO TO 9999
C
C  UNABLE TO FIND WHAT WE ARE LOOKING FOR.
C
 9000 CONTINUE
      CALL ZMOVE(CRNAME,BLANK)
      CALL ZMOVE(CANAME,BLANK)
      LOCATT = 1
      CROW = 0
      LROW = 0
 9999 CONTINUE
      RETURN
      END
