      FUNCTION NCODEI(INUM,ND)
C
C  PURPOSE:   ENCODE INUM INTO THE LEADING ND CHARACTERS OF A WORD
C
C  AUTHOR:    WAYNE J. ERICKSON   13 JULY 1979
C
C  PARAMETERS:
C     INPUT:  INUM----AN INTEGER NUMBER
C             ND------THE NUMBER OF DIGITS
C     OUTPUT: NCODEI--THAT NUMBER IN DISPLAY CODE USING ND CHARACTERS
C
C  DATA AND DIMENSION:
C
      INTEGER WORD
C
C  CALL INTCOD TO CONVERT THE NUMBER.
C
      CALL INTCOD(WORD,1,ND,INUM)
      NCODEI = WORD
      RETURN
      END
