      SUBROUTINE NXTCHX(CH)
C
C --- TEXT PARSING ROUTINE
C
C     PUT A CHARACTER AT THE FRONT OF THE INPUT STREAM
C     (INVERSE OF NXTCHR)
C
C     PARAMETERS
C              CH  =  CHARACTER TO REPLACE
C
      INCLUDE 'syspar.d'
      INCLUDE 'ascpar.d'
      INCLUDE 'cards.d'
      INCLUDE 'maccom.d'
C
C     CH MAY BE REPLACED IN THE MACRO BUFFER OR IN THE CARD BUFFER
C
      IF (MACWPT.LT.MACWPZ) THEN
         MACWPT = MACWPT - 1
         IF (MACWPT.LT.1) GOTO 8000
         CALL PUTT(MACWRK,MACWPT,CH)
      ELSE
         IF (CRDPTR.LT.1) GOTO 8000
         CALL PUTT(CRDREC,CRDPTR,CH)
         CRDPTR = CRDPTR - 1
      ENDIF
      RETURN
 
8000  PRINT *,'NXTCHX ERROR: ',MACWPT, CRDPTR
      RETURN
      END
