      FUNCTION RMTYPT(TYPE)
      INCLUDE 'syspar.d'
C
C     RETURN THE CHARACTER LABEL OF A RMTYPE CODE (KZXXXX)
C
      INCLUDE 'rmatts.d'
C
      RMTYPT = '    '
      IF (TYPE.EQ.KZINT ) RMTYPT = 'INT '
      IF (TYPE.EQ.KZDATE) RMTYPT = 'DATE'
      IF (TYPE.EQ.KZTIME) RMTYPT = 'TIME'
      IF (TYPE.EQ.KZREAL) RMTYPT = 'REAL'
      IF (TYPE.EQ.KZTEXT) RMTYPT = 'TEXT'
      IF (TYPE.EQ.KZDOUB) RMTYPT = 'DOUB'
      IF (TYPE.EQ.KZRVEC) RMTYPT = 'RVEC'
      IF (TYPE.EQ.KZIVEC) RMTYPT = 'IVEC'
      IF (TYPE.EQ.KZDVEC) RMTYPT = 'DVEC'
      IF (TYPE.EQ.KZRMAT) RMTYPT = 'RMAT'
      IF (TYPE.EQ.KZIMAT) RMTYPT = 'IMAT'
      IF (TYPE.EQ.KZDMAT) RMTYPT = 'DMAT'
      RETURN
      END
