      SUBROUTINE RMZIP(*)
      INCLUDE 'syspar.d'
C
C  PURPOSE:  PROCESS ZIP COMMAND  (CALL SYSTEM FUNCTION)
C
      INCLUDE 'flags.d'
      INCLUDE 'cflags.d'
      INCLUDE 'rmatts.d'
      INCLUDE 'tokens.d'
      INCLUDE 'cards.d'
C
      CHARACTER*1 CHRASC
C
      CHARACTER*80 CCARD
      LOGICAL SAVDF
      LOGICAL EQKEYW
C
      IF (ITEMS.LT.2) GOTO 910
 
      CCARD = ' '
      IF (.NOT.TOKTYP(2,KXTEXT)) GOTO 910
      NC = IDL(2)
      IF (NC.GT.80) GOTO 910
      CALL STRASC(CCARD,ASCREC(IDP(2)),IDL(2))
C
C     EXECUTE THE  COMMAND VIA SYSTEM DEPENDENT ROUTINE
C     CLOSE THE DATABASE IN CASE OF NO RETURN
C
      SAVDF = DFLAG
      IF (SAVDF) CALL RMCLOS
      CALL SYSCMD(CCARD,IERR)
      IF (SAVDF) CALL DBOPEN(DBFNAM,.FALSE.)
      CALL MSG(' ','RETURN FROM SYSTEM',' ')
      IF (IERR.NE.0) THEN
         CALL MSG('E',', CODE =','+')
         CALL IMSG(IERR,6,' ')
      ENDIF
      GOTO 999
C
910   CALL WARN(4,0,0)
      GOTO 999
C
999   RETURN 1
      END
