      FUNCTION TOKTYP(I,TYPE)
      INCLUDE 'syspar.d'
C
C     THIS FUNCTION CHECKS IF THE I'TH TOKEN IS OF TYPE 'TYPE'
C
C     INPUT - I........ITEM NUMBER
C             TYPE.....TYPE TO MATCH
C     OUTPUT- TOKTYP ...TRUE IF THE ITEM CAN BE OF TYPE 'TYPE'
C
      INCLUDE 'tokens.d'
C
C     FOR SUN FORTRAN I REPLACED IAND WINT AND
      IF (AND(IDT(I),TYPE).NE.0) THEN
         TOKTYP = .TRUE.
      ELSE
         TOKTYP = .FALSE.
      ENDIF
      RETURN
      END
