      SUBROUTINE TYPER(ATYPE,VECMAT,TYPE)
      INCLUDE 'syspar.d'
C
C     THIS ROUTINE TURNS RIM TYPES SUCH AS IVEC
C     INTO TWO USEFUL TYPES.
C
C     ATYPE...RIM TYPE (WITH VECTOR AND MATRIX INFO)
C     VECMAT..KZSCA,KZVEC,KZMAT
C     TYPE....KZINT,KZREAL,KZDOUB,KZTEXT,KZDATE,...
C
      INCLUDE 'rmatts.d'
C
      TYPE = 0
C
C     VECTORS
C
      VECMAT = KZVEC
      IF(ATYPE.EQ.KZIVEC) TYPE = KZINT
      IF(ATYPE.EQ.KZRVEC) TYPE = KZREAL
      IF(ATYPE.EQ.KZDVEC) TYPE = KZDOUB
      IF (TYPE.NE.0) RETURN
C
C     MATRICES
C
      VECMAT = KZMAT
      IF(ATYPE.EQ.KZIMAT) TYPE = KZINT
      IF(ATYPE.EQ.KZRMAT) TYPE = KZREAL
      IF(ATYPE.EQ.KZDMAT) TYPE = KZDOUB
      IF (TYPE.NE.0) RETURN
C
C     ALL ELSE ARE SCALER
C
      VECMAT = KZSCA
      TYPE = ATYPE
C
      RETURN
      END
