      FUNCTION UPCASE(ASCHR)
      INCLUDE 'syspar.d'
C
C     RETURN THE UPPER CASE EQUIVALENT OF ASCHR (ASCII-CHAR)
C
      PARAMETER (LA=97,LZ=122,OFF=97-65)
C
C
      IF (ASCHR.LT.LA .OR. ASCHR.GT.LZ) THEN
         UPCASE = ASCHR
      ELSE
         UPCASE = ASCHR - OFF
      ENDIF
      RETURN
      END
