      SUBROUTINE ZEROIT(ARRAY,NWDS)
C
C  PURPOSE:   ZERO OUT AN ARRAY
C
C  PARAMETERS:
C         ARRAY---ARRAY TO BE ZEROED OUT
C         NWDS----NUMBER OF WORDS IN THE ARRAY
C
      INTEGER ARRAY(1)
      DO 100 I=1,NWDS
      ARRAY(I) = 0
  100 CONTINUE
      RETURN
      END
