MODULE_TOPDIR = ..

include $(MODULE_TOPDIR)/include/Make/Dir.make



SUBDIRS = \
	d.correlate \
	d.monsize \
	d.mvmon \
	d.out.gpsdrive \
	d.out.png \
	d.out.file \
	d.polar \
	d.rast.leg \
	d.redraw \
	d.resize \
	d.slide.show \
	d.split \
	d.vect.thematic \
	db.test \
	g.manual \
	g.mlist \
	g.mremove \
	i.fusion.brovey \
	i.image.mosaic \
	i.landsat.rgb \
	i.oif \
	i.spectral \
	i.in.spotvgt \
	i.tasscap \
	m.proj \
	r.blend \
	r.fillnulls \
	r.in.aster \
	r.in.onearth \
	r.in.srtm \
	r.in.wms \
	r.mapcalculator \
	r.out.gdal \
	r.plane \
	r.reclass.area \
	r.regression.line \
	r.shaded.relief \
	r.tileset \
	r.univar.sh \
	v.build.all \
	v.convert.all \
	v.db.addcol \
	v.db.addtable \
	v.db.droptable \
	v.db.reconnect.all \
	v.db.update \
	v.in.garmin \
	v.in.e00 \
	v.in.gns \
	v.in.gpsbabel \
	v.in.mapgen \
	v.in.sites.all \
	v.rast.stats \
	v.report \
	v.univar.sh \
	v.what.vect

default: subdirs

clean: cleansubdirs
