MODULE_TOPDIR = ..

include $(MODULE_TOPDIR)/include/Make/Dir.make

SUBDIRS = \
	d.rast.leg \
	d.redraw \
	d.slide.show \
	g.manual \
	g.projinfo \
	i.spectral \
	pg.postgisdb \
	r.out.gdal \
	r.univar \
	v.shape.regist

default: subdirs

clean: cleansubdirs
