MODULE_TOPDIR = ..

include $(MODULE_TOPDIR)/include/Make/Dir.make

SUBDIRS = \
	d.redraw \
	g.manual \
	g.projinfo \
	pg.postgisdb \
	r.out.gdal \
	r.univar \
	v.shape.regist

default: subdirs

clean: cleansubdirs
