s/GS_P2distance/GSU_P2distance/g
s/GS_distance/GSU_distance/g
s/GS_dv3norm/GSU_dv3norm/g
s/GS_geodistance/GSU_geodistance/g
s/GS_v2dir/GSU_v2dir/g
s/GS_v3add/GSU_v3add/g
s/GS_v3cross/GSU_v3cross/g
s/GS_v3dir/GSU_v3dir/g
s/GS_v3eq/GSU_v3eq/g
s/GS_v3mag/GSU_v3mag/g
s/GS_v3mult/GSU_v3mult/g
s/GS_v3norm/GSU_v3norm/g
s/GS_v3normalize/GSU_v3normalize/g
s/GS_v3sub/GSU_v3sub/g
