
#define viewport gl_null
#define finish gl_null
#define getgdesc gl_null
#define mmode gl_null
#define doublebuffer gl_null
#define lsetdepth gl_null
#define zbuffer gl_null
#define czclear gl_null
#define getviewport gl_null
#define fminit gl_null
#define fmfreefont gl_null
#define fmfindfont gl_null
#define fmscalefont gl_null
#define fmsetfont gl_null
#define fmgetfontinfo gl_null
#define strwidth gl_null
#define fmgetstrwidth gl_null
#define frontbuffer gl_null
#define cpack gl_null
#define cmov2 gl_null
#define getcpos gl_null
#define fmprstr gl_null
#define charstr gl_null
#define lmcolor gl_null
#define circ gl_null
#define sphmode gl_null
#define sphdraw gl_null
#define zwritemask gl_null
#define backface gl_null
#define frontface gl_null
#define linewidth gl_null
#define bgntmesh gl_null
#define endtmesh gl_null
#define swaptmesh gl_null
#define bgnpolygon gl_null
#define endpolygon gl_null
#define bgnline gl_null
#define endline gl_null
#define shademodel gl_null
#define backbuffer gl_null
#define swapbuffers gl_null
#define popmatrix gl_null
#define pushmatrix gl_null
#define scale gl_null
#define translate gl_null
#define rot gl_null
#define n3f gl_null
#define v3f gl_null
#define lmdef gl_null
#define lmbind gl_null
#define readsource gl_null
#define lrectread gl_null
#define blendfunction gl_null
#define clipplane gl_null
#define makeobj gl_null
#define genobj gl_null
#define closeobj gl_null
#define mapw gl_null
#define perspective gl_null
#define loadmatrix gl_null
#define lookat gl_null
