.TH s.univar
.SH NAME
\fIs.univar\fR \- Univariate statistics for a GRASS sites list.
.br
.I (GRASS Sites Program)
.SH SYNOPSIS
\fBs.univar\fR
.br
\fBs.univar help\fR
.br
\fBs.univar\fR [\fB-agq\fR] \fBsites\*=\fIname\fR 
.SH DESCRIPTION
.I s.univar
calculates univariate statistics of floating point attributes of sites lists. 
This includes the number of sites, mean,
standard deviation, coefficient of variation,
mininum, first quartile, median, third quartile,
and maximum.
.SH OPTIONS
\fBFlags:\fR
.IP \fB-a\fR 18
Use all sites found in the named \fIsites\fR file, rather than
limiting output to sites falling within the current geographic region.
.IP \fB-g\fR 18
Print the statistics in shell script style (similar to \fIg.region\fR).
.IP \fB-q\fR 18
Quiet. Cut out the chatter.
.LP
\fBParameters:\fR
.IP \fBsites\*=\fIname\fR 18
Name of an existing sites file.
.SH SEE ALSO
.I s.normal
.SH BUGS
Needs to do as many calculations as possible without storing individual site
records (requires a lot of memory).
.br
Please send all bug fixes and comments to the author.
.SH AUTHOR
James Darrell McCauley, Agricultural and Biological Engineering, Purdue University 
.if n .br 
(mccauley@ecn.purdue.edu)
