#!/bin/sh
# Bourne (Korn) shell script for installation of MAPGEN/PLOTGEN
# software distributed in this directory subsystem.
# This a hell or high-water procedure where we attempt to do as
# much as possible with error returns dumped in install.mon

# troff font descriptor library
font=/usr/lib/font/devGRAPH

# ensure shell to be executed by 'make' will be Bourne
SHELL=/bin/sh

# set GRAPH to current path
GRAPH=/usr/mapgen
export GRAPH

#if you want the GRASS interface set GRASS to path to grass
if test "$GRASS" = ""; then
	echo -n "Enter the path to the GRASS source (ie /usr/grass3)? "
	read GRASS
	export GRASS
fi

#set RANLIB variable
RANLIB=ranlib
export RANLIB

MON=${GRAPH}/install.mon

# set monitor file
echo "GRAPH Installation on" `date` >$MON

# check RANLIB set
if [ ${RANLIB:-x} = "x" ] ; then
	echo "RANLIB not set!" | tee /dev/tty >>$MON
	echo "set environment parameter RANLIB to either echo or ranlib"
	exit 1
fi

# install plotter
cd graphics/plotter
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
#The following commented out code for sun machines without GRASS
#if [ -f /usr/lib/libsunwindow.a ] ; then
## Install sundump for Sun 3/4 systems
#	make -f Makesun install
#	if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
#	echo `pwd` "Sun Modules:" "INSTALL:" $E >>$MON
#else
#	echo "non-Sun system" | tee /dev/tty >>$MON
#fi
cd $GRAPH/src

# install tests
cd graphics/tests
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
cd $GRAPH/src

# Install troff fonts
if [ -d $font ] ; then
	echo "test" >${font}/test
	if [ $? = 0 ] ; then
		rm ${font}/test
# Install troff fonts
		cd graphics/fonts/troff
		make install
		if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
		echo `pwd` "INSTALL:" $E >>$MON
		cd $GRAPH/src
	else
		echo "can't write to troff directory $font" | \
			tee /dev/tty >>$MON
	fi
else
	echo "troff directory $font doen't exist" | \
		tee /dev/tty >>$MON
fi

# install plotter fonts
cd graphics/fonts
Makefonts ${GRAPH}/gfonts
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
cd $GRAPH/src

# Install basic MAPGEN/PLOTGEN support library
cd lib/Libgen
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
cd $GRAPH/src

# Install PLOTGEN sub-system
cd plotgen
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
#the following commented out code for sun system not using GRASS
#if [ -f /usr/lib/libsunwindow.a ] ; then
## Install szoom for Sun 3/4 systems
#	make -f Makesun install
#	if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
#	echo `pwd` "Sun Modules:" "INSTALL:" $E >>$MON
#else
#	echo "non-Sun system" | tee /dev/tty >>$MON
#fi
cd $GRAPH/src

# Install MAPGEN sub-system

# Install proj
cd proj
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
cd $GRAPH/src

# Install mapgen programs
cd mapgen
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
cd $GRAPH/src

# install coastline procedures
cd mapgen/coast
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
cd $GRAPH/src

# Install bivariate support program
cd mapgen/bivar
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
cd $GRAPH/src

# Install definition program: mapdef
cd mapgen/mapdef
make install
if [ $? -eq 0 ];then E="OK";else E="ERROR";fi
echo `pwd` "INSTALL:" $E >>$MON
cd $GRAPH/src

echo "
export GRAPHB
GRAPHB=${GRAPH}/bin/plotter:${GRAPH}/lib/gfonts/:sr:
PATH=${GRAPH}/bin:${PATH}" >sh_locenv

echo "
setenv GRAPHB ${GRAPH}/bin/plotter:${GRAPH}/lib/gfonts/:sr:
setenv PATH ${GRAPH}/bin:${PATH}" >csh_locenv

if [ ${GRASS:-x} != "x" ] ; then
echo "Installing the GRASS/MAPGEN interface" >> $MON
cd grass3.1
./makeall
cd $GRAPH/src
fi

echo "MAPGEN/PLOTGEN install complete on" `date` | tee /dev/tty >>$MON

exit 0
