#!/bin/sh

MAXVAL=4


until
d.font romans
i=`d.menu << 'EOF'
# set the text size in % of entire screen height
.S 3
# set the top edge
.T 10
# set the LEFT edge
.L 10
Overview: choose item of interest 
  GRASS
  Hardware
  People requirements
  Return
EOF
`

if [ $i -ge $MAXVAL ] 
	then
	exit 1
fi

$0.$i

do
echo -n
done
