CFLAGS = -g -Wall -DGNGRP_STATS
LNFLAGS =
OBJECTS = avl.o tree.o heap.o graph.o helpers.o graph_v1.o
INCLUDES = avl.h tree.h heap.h graph.h type.h graph_v1.h helpers.h
LIBRARY = libdgl.a

$(LIBRARY): $(OBJECTS) $(INCLUDES)
	ar r $@ $(OBJECTS); ranlib $@

.c.o:
	cc -c $(CFLAGS) $< -o $@

clean:
	rm -f *.o *.a
