.TH GPOLY2 1
.SH NAME
Gpoly2 \- extract areas from a cell map into a vector map
.SH SYNOPSIS
.B Gpoly2
cell_map vector_map
.SH DESCRIPTION
.I Gpoly2
like Gpoly,
scans the named cell_map and extracts lines which will separate it
into areas and creates the named vector_map.

.I Gpoly2
will create a vector map from a given cell map.  It will outline 
each unique area in the cell map and create vector data to represent it.
The cell values will be used to create attribute information for the
resultant vector areas.  After these areas are created, 
.I Gpoly2,
rounds off the corners by taking the midpoints of each line segment
(which are the height or width of a cell)
and saving the area using these
midpoints to define the new line segments.  
This usually results in a better looking vector map.  However, the
resulting vector map is not "true" to the cell map that it was created
from.  
In addition, the resulting vector map
is about 30% larger than the vector map
created by 
.I Gpoly.

.SH NOTES
When the new command line parsing function is available for the upper
case "G" commands, \fIGpoly2\fR will be merged with Gpoly and a
command line option will select smoothed or non-smoothed lines.

.SH BUGS
.I Gpoly2
extracts areas only.  If the cell file contains something which
you don't think of as an area, the result may be suprising.

.P
You will need to run 
.I support.vect
on the resultant files to build the dig_plus information.

.SH "SEE ALSO"
\fIsupport.vect[1]\fR

.SH "AUTHOR"
Gpoly - Jean Ezell, U.S. Army Construction Engineering Research Laboratory

Modified for smoothed lines - David B. Satnik, Central Washington University

