.TH s.in.grid
.SH NAME
\fIs.in.grid\fR\ \- convert Arc GRIDASCII output to site list.
.br
.I "(GRASS Shell Script)"
.SH SYNOPSIS
.B s.in.grid file
.SH DESCRIPTION
.I s.in.grid
is a awk shell (awk(1)) script that reads the output of
Arc/INFO's GRIDASCII command and converts it to a GRASS
site list.
.LP
\fBParameters:\fR
.IP \fIfile\fR 18
Name of the output of GRIDASCII.
.LP
.SH EXAMPLE
Typing the following:
.LP
.RS
Arc: \fBGRIDASCII nitrates tmp\fR
.br
Arc: \fBquit\fR
.br
GRASS GRID> \fBs.in.grid tmp | s.in.ascii nitrates fs='|'\fR
.br
GRASS GRID> \fBrm tmp\fR
.RE
.LP
exports the GRID file \fBnitrates\fR from Arc/INFO and imports
it as the GRASS site list \fBnitrates\fR.
.SH FILES
$GISBASE/scripts/s.in.grid
.SH SEE ALSO
.I s.in.ascii
.SH AUTHOR
James Darrell McCauley, Purdue University 
.if n .br 
(mccauley@ecn.purdue.edu)

