#ifndef _GRASS_RASTER_H
#define _GRASS_RASTER_H
#include "monitors.h"
int R_box_abs(int,int,int,int);
int R_box_rel(int,int);
int R_call_update_function ( int, int );
int R_color_table_float(void);
int R_color_table_fixed(void);
int R_color_offset(int);
int R_color(int);
int R_standard_color(int);
int R_cont_abs(int,int);
int R_cont_rel(int,int);
int R_erase(void);
int R_flush(void);
int R_font(char *);
int R_get_cancel(void);
int R_get_color_index(float,float,float);
int R_get_num_colors (int *);
int R_get_text_box( char *, int *,int *,int *,int *);
int R_get_location_with_box(int,int,int *,int *,int *);
int R_get_location_with_line( int,int, int *,int *, int *);
int R_get_location_with_pointer(int *,int *,int *);
int R_move_abs(int,int);
int R_move_rel(int,int);
int R_panel_save(char *name, int,int,int,int);
int R_panel_restore(char *name );
int R_panel_delete(char *name );
struct MON_CAP *R_parse_monitorcap(int, char *);
int R_polydots_abs(int *,int *,int);
int R_polydots_rel( int *,int  *, int);
int R_polyline_abs(int *,int  *, int);
int R_polyline_rel(int *,int *, int);
int R_polygon_abs(int *,int *, int);
int R_polygon_rel( int *,int *, int);
int R_RGB_color(unsigned char,unsigned char,unsigned char);
int R_set_RGB_color(unsigned char *,unsigned char *,unsigned char *);
int R_RGB_raster(int,int,unsigned char *,unsigned char *,unsigned char *,unsigned char *);
int R_raster(int,int,int,int *);
int R_raster_char( int, int, int, unsigned char  *);
int R_raster_int( int, int, int, int  *);
int R_reset_color( unsigned char,unsigned char,unsigned char, int);
int R_reset_colors( int,int, unsigned char *,unsigned char *,unsigned char *);
int R_screen_left(void);
int R_screen_rite(void);
int R_screen_bot(void);
int R_screen_top(void);
void R_set_cancel(int);
int R_set_window(int,int,int,int);
void R_set_update_function ( int (*fnc)( int, int ) ) ;
int R_text(char *);
int R_text_rotation(float);
int R_text_size( int,int);
int _send_ident(int);
int _send_char ( unsigned char *);
int _send_char_array(int, unsigned char *);
int _send_int_array(int,int *);
int _send_float_array(int, float *);
int _send_int( int *);
int _send_float( float *);
int _send_text( char *);
int _get_char( char *);
int _get_int(int *);
int _get_float(float *);
int _get_text(char *);
char *_get_text_2(void);
int _get (char *,int);
int flushout(void);
int R_open_driver(void);
int R__open_quiet(void);
int _hold_signals (int);
int R_kill_driver(void);
int R_close_driver(void);
int R_release_driver(void);
int R_stabilize(void);
int R_pad_append_item ( char *, char *, int);
int R_pad_delete_item ( char *);
int R_pad_get_item ( char *, char ***, int *);
int R_pad_list_items ( char ***, int *);
int R_pad_set_item ( char *, char *);
int _get_list ( char ***, int *);
int R_pad_freelist ( char **, int);
int R_pad_create ( char *);
int R_pad_current ( char *);
int R_pad_delete (void);
int R_pad_invent (char *);
int R_pad_list ( char ***, int *);
int R_pad_select (char *);
int R_pad_perror (char *,int);

/* freetype */
int R_font_freetype(char *);
int R_font_freetype_release();
int R_charset(char *);

#endif
