extern FILE *G_fopen_new() ;
extern FILE *G_fopen_old() ;
extern FILE *G_fopen_modify() ;
extern FILE *G_fopen_append() ;
extern FILE *G_fopen_sites_old();
extern FILE *G_fopen_sites_new();
extern FILE *G_fopen_vector_old();
extern FILE *G_fopen_vector_new();

extern CELL *G_allocate_cell_buf() ;
extern CELL  G_number_of_cats() ;
extern CELL  G_get_histogram_cat() ;

extern int **G_alloc_imatrix();
extern int *G_alloc_ivector();

extern long  G_get_histogram_count() ;

extern double G_database_units_to_meters_factor();
extern double G_northing_to_row();
extern double G_row_to_northing();
extern double G_easting_to_col();
extern double G_col_to_easting();
extern double G_adjust_east_longitude();
extern double G_adjust_easting();
extern double **G_alloc_matrix();
extern double *G_alloc_vector();

extern float **G_alloc_fmatrix();
extern float *G_alloc_fvector();

extern char **G_tokenize () ;
extern char *G__file_name () ;
extern char *G__getenv () ;
extern char *G__home () ;
extern char *G__location_path () ;
extern char *G__mapset_name () ;
extern char *G_ask_any () ;
extern char *G_ask_any_ext () ;
extern char *G_ask_cell_in_mapset () ;
extern char *G_ask_cell_new () ;
extern char *G_ask_cell_old () ;
extern char *G_ask_in_mapset () ;
extern char *G_ask_in_mapset_ext () ;
extern char *G_ask_new () ;
extern char *G_ask_new_ext () ;
extern char *G_ask_old () ;
extern char *G_ask_old_ext () ;
extern char *G_ask_sites_any () ;
extern char *G_ask_sites_in_mapset () ;
extern char *G_ask_sites_new () ;
extern char *G_ask_sites_old () ;
extern char *G_ask_vector_any () ;
extern char *G_ask_vector_in_mapset () ;
extern char *G_ask_vector_new () ;
extern char *G_ask_vector_old () ;
extern char *G_calloc() ;
extern char *G_color_name() ;
extern char *G_date() ;
extern char *G_database_unit_name();
extern char *G_database_projection_name();
extern char *G_ellipsoid_name();
extern char *G_find_cell () ;
extern char *G_find_cell2 () ;
extern char *G_find_file () ;
extern char *G_find_file2 () ;
extern char *G_find_sites () ;
extern char *G_find_sites2 () ;
extern char *G_find_vector () ;
extern char *G_find_vector2 () ;
extern char *G_fully_qualified_name () ;
extern char *G_get_ask_return_msg();
extern char *G_get_cat () ;
extern char *G_get_cats_title () ;
extern char *G_get_cell_title();
extern char *G_getenv () ;
extern char *G_gisbase() ;
extern char *G_gisdbase() ;
extern char *G_home () ;
extern char *G_lat_format_string();
extern char *G_location() ;
extern char *G_location_path() ;
extern char *G_lon_format_string();
extern char *G_malloc() ;
extern char *G_mapset() ;
extern char *G_mask_info() ;
extern char *G_myname() ;
extern char *G_program_name() ;
extern char *G_realloc() ;
extern char *G_recreate_command() ;
extern char *G_squeeze () ;
extern char *G_store () ;
extern char *G_tempfile () ;
extern char *G_tolcase () ;
extern char *G_toucase () ;
extern char *G_unit_name ();
extern char *G_whoami() ;
extern char *G_index() ;
extern char *G_rindex () ;
extern struct Flag *G_define_flag();
extern struct Option *G_define_option();

extern char * G_strcpy ();
extern char * G_chrcpy ();
extern char * G_strncpy ();
extern char * G_strmov ();
extern char * G_chrmov ();
extern char * G_strcat ();
extern char * G_chrcat ();
extern char * G_strstr ();
extern char * G_strdup ();

extern struct Key_Value * G_create_key_value();
extern struct Key_Value * G_fread_key_value ();
extern struct Key_Value * G_read_key_value_file();
extern struct Key_Value * G_get_projunits();
extern struct Key_Value * G_get_projinfo();
extern char * G_find_key_value ();
