#define SELECT "SELECT COUNT(*),SUM(%s),AVG(%s),MAX(%s),MIN(%s)\n"
#define CHKTYP "SELECT coltype FROM syscolumns WHERE colname="
#define FROM "FROM %s\n"
#define WHERE "WHERE %s IS NOT NULL\n"
#define SQL ".stats.sql"
#define TMP ".dbtmp.sql"
#define SQLOUT ".stats.out"
#define COUNT "count(*)"
#define SUM "sum"
#define AVG "avg"
#define MAX "max"
#define MIN "min"
#define FREQ "freq"
#define MODE "mode"
