
MODULE_TOPDIR = ../..

SUBDIRS = \
	lib \
	v.lrs.create \
	v.lrs.segment \
	v.lrs.label \
	v.lrs.where

#to install documentation:
PGM = lrs

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs htmldir

clean: cleansubdirs

