set test "GRASS enviroment settings test"
set ok 1
puts $env(GISBASE)
if { "$env(GISBASE)" == "" } {
    fail "GISBASE not set"
    set ok 0
}
puts $env(GISDBASE)
if { "$env(GISDBASE)" != "/tmp" } {
    fail "GISDBASE not set"
    set ok 0
}
puts $env(LOCATION)
if { "$env(LOCATION)" != "/tmp/grasstestsuite" } {
    fail "LOCATION not set"
    set ok 0
}
puts $env(LOCATION_NAME)
if { "$env(LOCATION_NAME)" != "grasstestsuite" } {
    fail "LOCATION_NAME not set"
    set ok 0
}
puts $env(MAPSET)
if { "$env(MAPSET)" != "PERMANENT" } {
    fail "MAPSET not set to PERMANENT"
    set ok 0
}
if { $ok == 1 } {
    pass "GRASS enviroment settings test"
}