.TH v.mkgrid
.SH NAME
\fIv.mkgrid\fR \- Creates a (binary) GRASS vector map of a user-defined grid.
.br
.I (GRASS Vector Program)
.SH SYNOPSIS
.B v.mkgrid
.br
.B v.mkgrid help
.br
\fBv.mkgrid\fR \fBmap\*=\fIname\fR \fBgrid\*=\fIrows,columns\fR \fBcoordinate\*=\fIx,y\fR \fBbox\*=\fIlength,width\fR [\fBangle\*=\fIdegree\fR]
.SH DESCRIPTION
\fIv.mkgrid\fR will create a binary format, vector map representation of a
regular coordinate grid.
.LP
\fBFlags:\fR
.IP \fB-q\fR 20
Quiet. Cut out the chatter.
.LP
\fBParameters:\fR
.IP \fBmap\*=\fIname\fR 20
Name to be assigned to binary vector map layer output.
.IP \fBgrid\*=\fIrows,columns\fR 20
Number of ROWS and COLUMNS to appear in grid.
.IP \fBcoordinate\*=\fIx,y\fR 20
Lower left EASTING and NORTHING coordinates of vector map layer output.
.IP \fBbox\*=\fIlength,width\fR 20
LENGTH and WIDTH of boxes in grid.
.IP [\fBangle\*=\fIdegree\fR] 20
optional rotate grid counter-clockwise about the origin (\fBcoordinate\fR).
.LP
If the user simply types \fBv.mkgrid\fR on the command line without
specifying parameter values, the program will prompt the user for inputs
using the standard interface described in the manual entry for \fIparser\fR.
.SH NOTES
The new binary vector map output is placed under the \fIdig\fR directory
in the user's current mapset, and can be used like any vector map layer.
Run \fIv.support\fR to build the topology information for the vector map
before using \fIv.mkgrid\fR map layer outputs in the \fIv.digit\fR program.

Since the grid is computer-generated, the corner coordinates will be exact
and can be used when patching together several \fIv.mkgrid\fR grids.

This is NOT to be used to generate a vector map of USGS quadrangles,
because USGS quads are not exact rectangles.
To generate a vector map of USGS quads, use the program \fIv.mkquads\fR.

The program ignores the current GRASS geographic region settings.  It will
create the complete grid even if part of this grid falls outside the current
geographic region.

Rotating the grid should not usually be necessary under normal usage, but 
this option is available.
.SH SEE ALSO
.I v.digit,
.I v.mkquads,
.I v.patch,
.I v.support
and
.I parser
.SH AUTHOR
Michael Higgins, U.S. Army Construction Engineering Research Laboratory
