MODULE_TOPDIR = ../..

PGM = r.digit

LIBES = $(DISPLAYLIB) $(RASTERLIB) $(GISLIB) $(VASKLIB) $(CURSES)
DEPENDENCIES = $(DISPLAYDEP) $(RASTERDEP) $(GISDEP) $(VASKDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
