EXTRA_CFLAGS = $(XCFLAGS) $(XINCPATH) $(XMINCPATH)
LIBS = $(XGILIB) $(XGDLIB) $(GISLIB) $(XMLIBPATH) $(XMLIB) $(XTLIBPATH) \
	$(XTLIB) $(XLIBPATH) $(XLIB) $(XEXTRALIBS)

all:: $(BIN)/xgbuffer

OBJS = \
	xgbuffer.o 

$(BIN)/xgbuffer: $(OBJS) $(XGILIB) $(GISLIB)
	$(CC) -o $@ $(LDFLAGS) $(XLDFLAGS) $(EXTRA_LDFLAGS) $(OBJS) $(LIBS)

$(XGILIB) $(GISLIB): # 
