.TH s.to.vect
.SH NAME
\fIs.to.vect\fR \- Converts a GRASS site_lists file into a vector file.
.br
.I "(NRCS GRASS Sites Program)"
.SH SYNOPSIS
\fBs.to.vect\fR
.br
\fBs.to.vect help\fR
.br
\fBs.to.vect input\*=\fIname \fBoutput\*=\fIname\fR
.SH DESCRIPTION
\fIs.to.vect\fR converts GRASS site_lists file into vector files.
The resulting vector file can be treated as any other vector file.
The requirements of the site_lists file are standard
(i.e., a regular site_lists file format is required).
Site_lists file values are used as \fIdig_cats\fR category values.
.SH "COMMAND LINE OPTIONS"
\fBParameters:\fR
.IP \fBinput\*=\fIname\fR 18
Name of input GRASS site_lists file to be converted.
.IP \fBoutput\*=\fIname\fR 18
Name to be assigned to the vector output file.
.SH AUTHOR
R.L. Glenn, USDA, NRCS, NHQ-ITC

