static char aline[80], answer[14], AZONE[5], null = '\0';
static char command[1024], sav_comd[1024], parms[256];
static char buff[300], in_file[60], out_file[60];
char *ptr, STabbr[2], COname[30], FIPSfile[60], TXT_ZONE[5];
char ellps_name[20], proj_name[20];
int ier, icode, SFIPS, CFIPS, fipscode, COzone, NUM_ZON, lookup;
int record, reccnt;
int i, conv_typ, conv_way;
int input_typ, output_typ, rec_cnt;
int IDEG,IMIN,JDEG,JMIN,ST_zone,ZONE;
float XDEG,XMIN,YDEG,YMIN,Q,XSEC,YSEC;
double LAT, LON;
double LONCEN, LATPAR, NOR, EAS;
char check; 
FILE *In_file, *Out_file, *Mem_file;
