 
SHLIB = $(ARCH_LIBDIR)/$(SHLIB_PREFIX)$(SHLIB_NAME).$(SHLIB_SUFFIX)

CFLAGS += $(SHCFLAGS)
LDFLAGS += $(SHLDFLAGS)

$(SHLIB): $(SHLIB_OBJS)
	$(CC) $(LDFLAGS) $(SHLIB_LD) $(EXTRA_LIBDIRS) $(LIBDIRS) $(TOOLS_LIBDIRS) \
		$(SHLIB_OBJS) $(EXTRA_LIBS) -o $@

shlib: $(SHLIB)


