
MODULE_TOPDIR = ../..

PGM = v.build.polylines

LIBES = $(VECTLIB) $(GISLIB) $(VASKLIB)
DEPENDENCIES = $(VECTDEP) $(GISDEP) $(VASKDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

