MODULE_TOPDIR = ../../..

PGM = r.li.patchAreaDistributionCV

LIBES = $(GISLIB) -L../r.li.daemon -lr_li
DEPENDENCIES = $(GISDEP) ../r.li.daemon/libr_li.a


include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
